### ISSUE TITLE
Connection string - inner loop - outer loop 

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-functions-dotnet-worker#1015]
Need to add Connection String in Azure portal after publishing the function from Visual Studio 

Connection string  is in local.settings.json and set the connection 

```
 [Function("QueueFunction")]
        public void Run([ServiceBusTrigger("melonqueue", Connection = "ServiceBusConnectionString")] string myQueueItem)
        {
            _logger.LogInformation($"Hello Geeks start ! ");
            _logger.LogInformation($"C# Queue trigger function processed: {myQueueItem}");         
            _logger.LogInformation($"Hello Geeks end ! ");
        }
```

There are some similar asks in the community.

**Comment by jviau** [comment]
@cloudmelon can you expand a bit on what you are asking for here? I ask because .NET - and Azure - already has a best practice for managing secrets like this. Are we aiming to build off of that, or role our own thing?

For starters, we _shouldn't_ recommend secrets in `local.settings.json` as that risks checking it in as part of source control. Instead, we should recommend [user secrets](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets).

**Comment by fabiocav** [comment]
@cloudmelon closing this in favor of the work we're doing to support the VS dependencies and connection references. Let us know if any additional information is required.
