### ISSUE TITLE
Azure Isolated Function for Server Sent Events

### ISSUE THREAD

**Issue by keerthiraaju** [Azure/azure-functions-dotnet-worker#1128]
For a project, I had created a poc sample for pushing data to browsers (server sent events) using the below example in **azure function -> dotnet 6.0 -> http-trigger** (in-process) and got it worked ..

TargetFramework   		----->   	net6.0
AzureFunctionsVersion	------>		v4
"FUNCTIONS_WORKER_RUNTIME": **"dotnet"**

**HttpRequestMessage** which supported for **PushStreamContent**

(HttpRequestMessage --> Request)  Example code link [here](https://github.com/keerthiraaju/Server-Sent-Events)

 var response = Request.CreateResponse();
            response.Content = new PushStreamContent(async (stream, httpContent, transportContext) =>
            {  
				....
                }
            }, "text/event-stream");
			
			
**Describe the bug**

TargetFramework   		----->   	net6.0
AzureFunctionsVersion	------>		v4
"FUNCTIONS_WORKER_RUNTIME": **"dotnet-isolated"** (out-of-process)

Same code tried to migrate using **Azure function - dotnet 6.0 -isolated - http-trigger** 
code structure is based on **HttpRequestData** it's not supported for **PushStreamContent** while doing so

Is there way of implementation is different instead of using PushStreamContent in the isolated azure function?
Thanks.

**Comment by jviau** [comment]
Unfortunately, we do not have the equivalent APIs in v4. This is because your response payload needs to be proxied over gRPC back to the worker before ultimately returning to the caller. The closest is [HttpResponseData.Body](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Core/Http/HttpResponseData.cs#L36). However, be aware that due to the way gRPC library works this stream **will be realized** before being sent back to the host.

This is a feature gap with v3 we are aware of and are exploring how we can address it, but nothing to share as of now.
