### ISSUE TITLE
Net 7 sample doesn't work on linux

### ISSUE THREAD

**Issue by kamyker** [Azure/azure-functions-dotnet-worker#1145]
Created linux function app net 7 in US West Azure and uploaded (using func cli) sample project from this repo.

It simply doesn't work, returns 503. Works after changing target to net6.0.

Was it even tested on linux?

Response I get:
```
<html>

<head>
	<title> Server Error </title>
</head>

<body>
	<font color=\"#aa0000\">
		<h2>Server Error.</h2>
	</font>

	There was an unexpected error in the request processing.
</body>

</html>
```

**Comment by kshyju** [comment]
@kamyker I was able to deploy the sample app to a Linux consumption app in west us region successfully and validated my http trigger function works fine. 

Keep in mind that the sample has an eventhub trigger which requires the eventhub connection string to be set in azure. For my testing. I commented out that function so my payload was only a net7 function app with http trigger.

If you are still running into issues, can you share your function name and timestamps so that we can investigate. 

[Sharing Your Function App name privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)

**Comment by kamyker** [comment]
I also removed the eventhub method. I moved to kubernetes in oracle instead of azure functions, I don't want to waste any more time but thanks for the help.
