### ISSUE TITLE
Anonymous type generation in function metadata generator can conflict with reserved C# keywords

### ISSUE THREAD

**Issue by jviau** [Azure/azure-functions-dotnet-worker#1154]
Repro steps:

1. Go to samples/Extensions/Extensions.csproj
2. Upgrade `Microsoft.Azure.Functions.Worker.Sdk` to `1.8.0-preview2`
3. Restore and build

Expected results:
Compiles without errors, source file is generated.

Actual results:
Build error:
> samples\Extensions\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionMetadataProviderGenerator\GeneratedFunctionMetadataProvider.g.cs(448,23): error CS0065: 'GeneratedFunctionMetadataProvider.': event property must have both add and remove accessors

The reason is that we are generating anonymous types for the extension bindings, and one of them has a property name "event", which when generated as an anonymous type property conflicts with the reserved C# keyword `event`. To help see the issue, you can add the build property `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>` to the Extensions.csproj and then view the file in the obj/Debug/net6.0/generated folder.

**Comment by satvu** [comment]
In #1131 the casing was standardized for the anonymous type that represents bindings and their properties. By using Pascal case for all of the anonymous type properties, we avoid conflicting with reserved C# keywords. 

Other generated variable names also will not conflict since they are named using a name that is not a keyword + a number to keep count (ex. Function1, Function2, Function1Binding1).

This issue and repro steps were created before the merging of #1131, and I verified that this bug is not reproducible anymore by creating a local sdk package with the latest changes and following the same steps.
