### ISSUE TITLE
Can we get Message and MessageReceiver objects in isolated functions

### ISSUE THREAD

**Issue by ranjeetkpGit** [Azure/azure-functions-dotnet-worker#1176]
Hi,
I understand, we don't have 'Message' and 'MessageReceiver' object in isolated functions. 
Is there any way we can extract 'Message' and 'MessageReceiver' objects  from FunctionContext?

[Function("Function1")]
public async Task ProcessMessageAsync(
            [ServiceBusTrigger("test-topic", "test-subscription",
                Connection = "ServiceBusConnection")]
            string message, FunctionContext context)
{
var messageReceiver = context.BindingContext.BindingData.GetValueOrDefault("MessageReceiver")
}

**Comment by victormarante** [comment]
Without knowing any details about _BindingData_ in general, I don't think this is a good approach. I think we should either:
1. Leave as is (i.e. you have to deserialize a primitive type (string in this case) to a service bus message or similar)
2. Work on allowing these types to be bound as part of the trigger definition.

Not sure what the team thinks on the topic, I know @kshyju has done some work on converters/binders. Not sure how far they got on the topic.

**Comment by fabiocav** [comment]
@ranjeetkpGit some of those capabilities are coming in for a number of extensions, but Service Bus is not yet one of those as it requires some additional enhancements to the underlying extension and SDKs due to the nature of the trigger.

So the short answer to this, today, is that it isn't supported, but although I don't have an ETA I can share for Service Bus, it is something we're actively working on.

**Comment by fabiocav** [comment]
Closing as answered, but please let us know if you need any additional information.

You can follow the issue tracking the binding enhancements here: https://github.com/Azure/azure-functions-dotnet-worker/issues/1081
