### ISSUE TITLE
How to perform dynamic configuration?

### ISSUE THREAD

**Issue by RobTF** [Azure/azure-functions-dotnet-worker#1238]
Hi,

Due to .NET 7 not supporting "normal" function apps, instead only allowing "isolated" my team and I are trying to port over some simple function apps to the isolated model.

The only problem we have encountered so far is that of configuration. We make heavy use of Azure app configuration as well as dynamic configuration for service bus based on logic which runs at startup.

The timer issue is probably simpler; we have tried

```csharp
var host = new HostBuilder()
    .ConfigureAppConfiguration(builder =>
    {
        builder.AddAzureAppConfiguration(options =>
        {
            options.Connect(Environment.GetEnvironmentVariable("CONFIG_CONN_STR"));
            options.Select("MyConfig:*");
        });
    })
    .ConfigureServices((ctx, services) =>
    {
        services.AddAzureAppConfiguration();
    })
    .ConfigureFunctionsWorkerDefaults(app =>
    {
        // Use Azure App Configuration middleware for data refresh.
        app.UseAzureAppConfiguration();
    })
    .Build();
```

then...

```csharp
    [Function("Cleanup")]
    public async Task CleanupAsync(
        [TimerTrigger("%MyConfig:Schedule%")] TimerInfo timerInfo)
    {
       // do stuff...
    }
```

However this appears to not work, instead giving the following;

```
Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.Cleanup'. Microsoft.Azure.WebJobs.Host: '%MyConfig:Schedule%' does not resolve to a value.
```

How does this work in isolated mode? The error seems to be thrown out to the console before any code is even run to mount the Azure Configuration stuff?

In addition, using the old, non isolated system we were able to manipulate the configuration for service bus triggers during startup, performing logic and manually adding keys to the application configuration using an in memory configuration provider. This is the same concept as above, only rather than using Azure Configuration the config values were based on a runtime calculation.

Whilst the old system complained lightly about stuff like "this might have side effects when auto scaling" everything worked fine and it fit our needs.

Can the isolated function stuff be made to work like this, or must we remain on .NET 6 for now?

thanks

**Comment by SeanFeldman** [comment]
Imperative binding is not currently working but is [planned](https://github.com/Azure/azure-functions-dotnet-worker/issues/1008) .

**Comment by RobTF** [comment]
@SeanFeldman It looks like imperative binding is listed under the *Permanent Differences* section of the page which is described as listing *...behaviors of the in-process model which we will not bring into the isolated worker.*. Does that mean that the plan is **not** to implement this? Could be a showstopper for a fair few use cases!

The workaround says to *[use] the corresponding service SDKs directly*, but what does that mean in the context of the configuration issue?

**Comment by SeanFeldman** [comment]
There's an [older issue](https://github.com/Azure/azure-functions-dotnet-worker/issues/303) where the same was asked and the issue wasn't closed. Perhaps worth reviving it.

**Comment by RobTF** [comment]
Ah great, thanks for clarification!

**Comment by fabiocav** [comment]
To clarify, the *imperative binding* item tracked in the linked issue is about the use of `IBinder` as described [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#binding-at-runtime).

The question is mostly about binding expressions, as described [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns#binding-expressions---app-settings). 

Today, binding expressions are resolved by the host, meaning that all the configuration sources must be registered with the host in order to be used for expression resolution. Unfortunately, this is not something that we currently support with the isolated model today. The closest thing that is supported today would be the configuration integration with [Key Vault References](https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli), or simply using App Settings for the site. 

We'll track this as an enhancement request #1253

**Comment by fabiocav** [comment]
Closing this as we have the issue I mentioned above tracking the work and linking to the details shared here. Please feel free to follow up there if needed.
