### ISSUE TITLE
.NET 6 Isolated Worker - AppInsights exception snapshots take snapshot of host, not worker

### ISSUE THREAD

**Issue by asyncmeow** [Azure/azure-functions-dotnet-worker#1245]
(Sorry if this is in the wrong repo, not sure if the host is a separate one)
I have an azure functions application running on the .NET 6 isolated runtime, with exception snapshots enabled for application insights. When the application hits an exception, it seems the snapshot is taken in the context of the host runtime, not the worker itself, as the exception shown inside the snapshot is an RpcException (not the exception thrown in the worker), and none of my code is in the stack trace shown in the snapshot: 
![image](https://user-images.githubusercontent.com/109551954/208474710-d92fe8de-2617-43bc-977b-18c73ad769da.png)

Is there a way to have the snapshot that's uploaded to application insights given in the context of the worker process instead of the host?

**Comment by fabiocav** [comment]
@kassienull this capability has been added to the worker, but since this changed the logging behavior, today it is an opt-in setting.

You can set the [EnableUserCodeExceptions](https://github.com/Azure/azure-functions-dotnet-worker/blob/f5a232c00eea67a49ca9e2db0aa774d69cba607c/src/DotNetWorker.Core/Hosting/WorkerOptions.cs#L29) property to true, similar to the following:

``` csharp
    var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(builder =>
    {
    }, options =>
    {
        options.EnableUserCodeExceptions = true;
    })
    .Build();
```

Also leaving this issue open so we can provide a better sample and documentation for this feature.

**Comment by inishantmishra** [comment]
Even after enabling the EnableUserCodeException = true in dotnet isolated Azure function, I am still receiving RPC exceptions with no call stack.
I thought by this change, if l throw some custom exception in my code and if I handle it and log it, I will not get the RPC exception but my custom exception in appInsights.
But still, I am receiving the RPC exception.

Let me know what am I missing? Why am i still receiving RPC exceptions?

I am using
dotnet-isolated
~4
.net 7 Isolated Azure function

**Comment by liliankasem** [comment]
Hi @inishantmishra, sorry about the delayed response.

The `EnableUserCodeException` capability was created to handle a specific scenario where AppInsights in the worker isn't an option and you need basic logging, and so the host is used to log some information to AppInsights. Via this model, custom exceptions do not work as we use Grpc to pass this information from the Worker -> Host, there is no way for the host to have any awareness of what your custom exceptions are, it does not have access to the Type.

If you want to see custom exceptions in AppInsights, you can follow [this guidance](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#application-insights) to enable AppInsights within the worker instead of depending on the host logging behaviour. This is the recommended way to enable logging for the isolated model. The host exception path is a legacy model that provides basic logging capabilities when Application Insights is not a viable option.

**Comment by mattchenderson** [comment]
Closing as the V2 worker package sets `EnableUserCodeException` by default. Docs reflect current best practice recommendations.
