### ISSUE TITLE
Accessing to RetryContext.RetryCount and MaxRetryCount throw exception

### ISSUE THREAD

**Issue by robertodelbuono** [Azure/azure-functions-dotnet-worker#1438]
In an isolated function for EventGridTrigger accessing FunctionContext.RetryContext.RetryCount and MaxRetryCount throw nullreferenceexception 

context.RetryContext?.RetryCount -> nullreferenceexception

**Comment by robertodelbuono** [comment]
Hi,
I configured it in the event grid subscription.

![image](https://user-images.githubusercontent.com/50736728/228511448-c92a5fb1-db26-4e48-90e2-6516f4cb2650.png)

**Comment by fabiocav** [comment]
@robertodelbuono services with built-in retry support (those with configuration done at the event source/subscription/host.json), the Functions retry policy feature is not used, so that context will not be populated.

We'll keep this issue open to address the null reference exception you're seeing, as that is a defect, but currently, the `RetryCount` and `MaxRetryCount` properties will not be populated for those services.
