### ISSUE TITLE
Worker SDK build failed when moving file.

### ISSUE THREAD

**Issue by YuiTH** [Azure/azure-functions-dotnet-worker#1513]
@fabiocav 
Our build pipeline seems randomly failing with reference multiple packages related to Microsoft.Azure.Functions.Worker.Extensions.*.
Error messages has multiple formats, but it always related to some kind of file lock or file move failed.

Here are some [logs we collected](https://microsoftapc-my.sharepoint.com/:f:/g/personal/yaobolun_microsoft_com/EvlR8fY9SBxErPW5kQ2-BYcBL8xU0yNPyU5eZp1epJsfxw?e=bqWJew)

And here are some insights from Rainer Sigwald: 
> In this case, I see two operations on the file that failed:
> Copying file from "C:\Users\xxx\AppData\Local\Temp\ymu02bvj.ere\publishout\Microsoft.Azure.WebJobs.Extensions.dll" to "C:\Users\xxx\AppData\Local\Temp\ymu02bvj.ere\publishout\bin\Microsoft.Azure.WebJobs.Extensions.dll".
> 
> Moving file from "C:\Users\xxx\AppData\Local\Temp\ymu02bvj.ere\publishout\Microsoft.Azure.WebJobs.Extensions.dll" to "C:\Users\xxx\AppData\Local\Temp\ymu02bvj.ere\publishout\bin\Microsoft.Azure.WebJobs.Extensions.dll".
> 
> The latter is the one that failed, the former seemed fine. The Move task is generally perfectly happy to overwrite files, so I’m not totally sure what’s going wrong here.
> 
> I wonder if antivirus software may be interfering with a deletion operation on a just-created-in-the-TEMP-folder DLL because it’s doing a scan operation.
> 
> Of course, it’s also a bit weird that something is both [copying](https://github.com/Azure/azure-functions-vs-build-sdk/blob/bbd305d9d7ced7a9635e864072a9f697b0152361/src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Build.targets#L70-L72) and [moving](https://github.com/Azure/azure-functions-vs-build-sdk/blob/bbd305d9d7ced7a9635e864072a9f697b0152361/src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Publish.targets#L144-L146) the same file to the same place. That’s something to ask the Azure Functions folks about, since it’s in their publish logic. That may be conflicting with the Azure Functions Worker logic to [hard-code PublishDir and OutputPath to the same place](https://github.com/Azure/azure-functions-dotnet-worker/blob/da59203a4c49776e94c5fa9ec0dd32d70f11024a/sdk/Sdk/Targets/Microsoft.Azure.Functions.Worker.Sdk.targets#L376) when building the generated WorkerExtensions.csproj. Can you help or route on this conflict and whether that duplication is intentional?

Our build pipeline should not be inference by any anti-virus machine since everyone in MSFT is using it. And remove reference of project with Worker.Function will mitigate the problem. Please help us to investigate this issue.

**Comment by YuiTH** [comment]
@jviau Any update on this? Our pipeline is blocked by this issue.

Any recommendation to mitigate this issue is also welcome: we don't mind to change our project or pipeline to reduce pipeline failure rate.

**Comment by YuiTH** [comment]
> @YuiTH this typically means something else has a lock on the file and the underlying OS will not allow for the move operation to be performed.
> 
> The warning you have linked is not related to our SDK, and is a general dotnet build step.

I've talked to MSBuild folks and was told WorkerExtension is suspicious. Please refer to the links in main thread.

> Given that you have experienced this warning with both one of our dlls (the original issue comment) and the `testhost.dll` linked there is unrelated. This makes me think the root issue is external to our SDK.

Remove Worker SDK from our project will always solve this issue. (We can't do that in production pipeline unfortunately since it will break our Azure Function) And every file lock either happens inside WorkerExtension.dll building or right after a WorkerExtension.dll build.

> I recommend disabling parallel build if you have it enabled and see if that helps.

We have no parallel build setup. Our build pipeline is serialized. We use standard OneBranch pipeline with standard container image.

**Comment by jviau** [comment]
For parallel, I meant the ability for MSBuild to perform parallel build itself: https://learn.microsoft.com/en-us/visualstudio/msbuild/building-multiple-projects-in-parallel-with-msbuild?view=vs-2022 - but again, not sure if you ever had it enabled. Looking at your CI file, I don't _think_ you do, but not entirely sure.

I am not sold this is a functions issue though - even after reading the additional information. When looking at your past CI failures I see a wide variety of failures relating to unable to access files, and only some of them have anything to do with functions. Several of them are trying to copy dlls from nuget packages.

Some other suggestions: I see your CI file has several independent `dotnet build` steps. I see that some of these build steps overlap the same projects. I could see the antivirus comment being true. Later builds fail as the antivirus is scanning the results of the already executed builds still.

Maybe you could consolidate down to a single `dotnet build` step. I recommend using the [msbuild traversal](https://github.com/microsoft/MSBuildSdks/blob/main/src/Traversal/README.md) SDK and a `ci.proj` file which brings in all the individual csproj's you care about. This will help remove redundant build steps.

**Comment by YuiTH** [comment]
I've successfully reproduced some of the issues in my devbox with only restore and one dotnet build executed. Errors can also come from the first build task in CI, right behind dotnet restore. For example, some projects will build WorkerExtension 2 times in a row and latter one will fail due to file locks. I'm not sure why WorkerExtension will build 2 times in one dotnet build command.

I will try that again locally with a stricter environment like docker and see if there any insights from log.

**Comment by jviau** [comment]
If it is an issue of not releasing handles on files, that would be an msbuild issue and not ours - as we are using tasks from them. As for the 'hardcoded' paths - while it is potentially _odd_ we are building & publishing to the same directory, there is nothing really outright wrong with that. Publish always happens after build, so the tasks are never running concurrently. Also, it is all the same process running both those copy & moves, so it would never be a file lock exception - since we would still have the lock.

This issue stems from _some other_ process holding into these files. I also don't believe it has anything to do with our SDK since it is even dll's in the nuget package directory that are locked, and we definitely don't have anything to do with that.

Now, if it is a case where `dotnet build` and `msbuild` by extension have a period of time where they keep file handles open post build, then moving to the single `ci.proj` file would help you out, as now all your different `.csproj`'s will be built in a single go, so no file handle issues between separate `dotnet build` runs.

There is also another benefit to `ci.proj` approach: cheaper builds. By splitting it up as you do now, you are potentially triggering redundant builds. Typically, incremental builds aim to make this less impactful, it is very easy for packages to break incremental builds if their targets are not authored with them in mind. Which I believe our SDK targets are not - we definitely do cause redundant work during an incremental build. This is something we can address, but not a high priority (incremental support is an optimization, not a requirement).

> About this part, do you mean we can leverage one dll multiple time if we write build script with msbuild traversal?

Yes, within a single `dotnet build` or `msbuild` invocation, MSBuild will only build a given project once per unique build arguments. Combining all you discrete `dotnet build` CI steps into a single one via traversal and `ci.proj`, you will get more efficient builds as MSBuild will be able to re-use build results of projects for common dependency chains.

> I have managed to reproduce some of the issues on my local machine with only "dotnet restore" and "dotnet build" executed. Since there are no redundant build steps in this case, it's difficult to tell that multiple build task cause locks. However, we can certainly give it a try to see if traversal helps.

What errors exactly do you get on your local repros? Is it always the same files? Or different ones?
