### ISSUE TITLE
Azure Isolated Function (Timer Trigger) is inconsistent with Async operations

### ISSUE THREAD

**Issue by ranjeetkpGit** [Azure/azure-functions-dotnet-worker#1649]
Hi,

I am using Azure Timer Trigger function and executing below on 20 records. It is inconsistent and skips records. 
Tried with Parallel.ForEachAsync and async both. Both options available in the code.
            
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/92055761/b725bd5d-c612-4ad5-a0b2-cb9acd3a9e57)

sample code - https://github.com/ranjeetkpGit/azure-function-worker/blob/e21febe85c31bbf0fe75e62745d071cd32af7056/TimerTriggerFunction.zip

**Comment by kshyju** [comment]
> skips one record

Can you elaborate this? How did you determine this? From the code you shared in the issue, I am not able to comprehend that.

The code you shared is using standard C# APIs (`Parallel.ForEachAsync`), nothing function specific. Does your code work if you try it outside function (a console app/ aspnet core app)? What does `GetDocumentsAsync` ? Is that where you are observing the "skip one record" behavior?

If you can provide more specific information about the actual behavior and minimal repro information, we are happy to take a look at it further.

**Comment by ranjeetkpGit** [comment]
> > skips one record
> 
> Can you elaborate this? How did you determine this? From the code you shared in the issue, I am not able to comprehend that.
> 
> The code you shared is using standard C# APIs (`Parallel.ForEachAsync`), nothing function specific. Does your code work if you try it outside function (a console app/ aspnet core app)? What does `GetDocumentsAsync` ? Is that where you are observing the "skip one record" behavior?
> 
> If you can provide more specific information about the actual behavior and minimal repro information, we are happy to take a look at it further.

Hi @kshyju , 
Thanks for reply. I have added details and sample code as zip. You can run it in VS 2022.

**Comment by kshyju** [comment]
_I see you updated the original post after my reply, some part of my last comment may look like it is irrelevant for the latest version of the OP. In the future, I suggest leaving a follow up comment with new code so the replies makes sense._

 Thank you for providing the repro app.  I was able to repro the behavior you were describing.

Like I mentioned in the previous response, It has nothing to do with functions, if you take that code to a console app and run many times, you will experience the same result (Inconsistent number of entries in the return value of `FindCountries` method).

Now let's take a closer look at your code:
```csharp
private async Task<List<string>> FindCountries()
{
    var countries = new List<string>();
    var tasks = _cities.Select(async city =>
    {
        if (await GetCityAsync(city))
        {
            countries.Add(city.Country);
        }
    });

    await Task.WhenAll(tasks);

    return countries;
}
```
You are awaiting `Task.WhenAll(tasks)`. `tasks` is a collection of tasks (specifically `IEnumerable<Task>`), where each of those task  contain the below code for the city passed into that delegate

```csharp
if (await GetCityAsync(city))
{
    countries.Add(city.Country);
}
```
When you do `await Task.WhenAll(tasks);` it is waiting for those tasks produced from the LINQ `Select` expression to finish, but there is nothing telling that those task should be considered [completed ](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskstatus?view=net-7.0)only when we get a result from `GetCityAsync` method. Because of this, it is possible that some of the `GetCityAsync` responses are coming after your `await Task.WhenAll(tasks);` is done executing.

What you need to do is rewrite the inner task to return a value. With this, your `await Task.WhenAll(tasks)` call will give you an array of result from the inner task. It could be either the country name if `GetCityAsync` returns true, else null)

```csharp
private async Task<List<string>> FindCountriesNew()
{
    var tasks = _cities.Select(async city =>
    {
        if (await GetCityAsync(city))
        {
            return city.Country;
        }

        return null;
    });

    var countriesFromAllTasks = await Task.WhenAll(tasks);
    // to do: If needed, filter out null entries from countriesFromAllTasks
    return countriesFromAllTasks.ToList();
}
```

Hope this helps. Please don't hesitate to reach out if you run into issues specific to azure functions.
