### ISSUE TITLE
HttpTrigger template missing Http extension

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-dotnet-worker#174]
Had to manually add this package to get the default template to build

    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.12-preview1" />

**Comment by ankitkumarr** [comment]
Thanks for reporting! I wasn't able to repro this on my end. I will double check. The post-install action to add this package may fail if the build of your function project failed. I have seen this before if I have some issues in my `csproj` (or an invalid reference), so adding new reference fails (no error is shown).

Wondering if you saw this with the newest packages (`1.0.1-preview5` Sdk and `1.0.0-preview5` Worker) and private core tools (`3.0.3320`).

**Comment by ankitkumarr** [comment]
Looking at your other issue  https://github.com/Azure/azure-functions-dotnet-worker/issues/173, I actually think that this happened in your case, because the dotnet5 project template is adding `1.0.1-preview5` and you may have been trying it before it was released :). So the action to add the Http package likely failed.
