### ISSUE TITLE
azure.functions.worker.http.extension needs to be updated

### ISSUE THREAD

**Issue by CaidenKehrer** [Azure/azure-functions-dotnet-worker#1810]
There are items in the unpublished version of the azure.functions.worker.http.extension package that is not included in the package on Nuget. It needs to be updated.

One example is the [FromBody] attribute.

**Comment by mattchenderson** [comment]
Hi - we will publish new packages when we are ready to cut a release. Is there a place where you see an unpublished version being referenced in a place it shouldn't be?

**Comment by liliankasem** [comment]
The release notes for 1.18.0 reference #1712 as it includes a change that was made to Core (1.14.0) and the notes are meant to clear that up:

> Unsealed InputConverterAttribute. Implementers can now derive from this type to map attributes to custom converters.

That PR just happened to make several different changes and will probably be mentioned in multiple release notes, like the http extension https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.Http/release_notes.md

> Added ability to bind a POCO parameter to the request body using FromBodyAttribute

That happens sometimes when a PR touches the Core and Extension packages, but I believe the HTTP package has not been published yet because it's not ready (@satvu or @brettsam might have more info).

**Comment by CaidenKehrer** [comment]
This is correct. The master branch contains code for binding a POCO parameter. Do we have an eta for the http package to be updated?

**Comment by JeroenvdBurg** [comment]
Looking forward to the release 😄 
would be great to use the new HTTP model binding feature #1712

**Comment by fabiocav** [comment]
Closing this as the extension has been released.
