### ISSUE TITLE
Issue when returning a signalr message causing a queue message to fail.

### ISSUE THREAD

**Issue by brandonseydel** [Azure/azure-functions-dotnet-worker#1825]
When using a queue input trigger and a signalr  output binding the queue message will refire N times if the signalr fails to process the result of the return.  I would like at least an option to fail silently (preferably a method I could pass to invoke) as there is no way to stop this.

**Comment by Y-Sindo** [comment]
It looks more like a question of how the dotnet-isolated worker and queue handle an output binding failure. From SignalR perspective, I can only image a solution that uses [Azure SignalR serverless SDK](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md) instead of SignalR output binding so that you can catch the exception and have your own error handling logic. 
@liliankasem Maybe experts for Queue trigger and dotnet worker have other insights.

**Comment by liliankasem** [comment]
You might be able to set the queue maxDequeueCount so that it doesn't fire after failure:

https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue?tabs=in-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp#host-json

Alternatively, you can write middleware to handle exceptions: https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/CustomMiddleware/ExceptionHandlingMiddleware.cs

**Comment by brandonseydel** [comment]
@liliankasem looks like the middleware fires before the function context middleware fires.  Max dequeue count I don't want to lower as I want retries if it fails for real.  Looks like I could do a couple of things, but it's all buried in internals and privates.  I am guessing the function executor, or something needs swapped.
