### ISSUE TITLE
How To: Isolated Functions App with Durable Functions + SignalR Self-Host

### ISSUE THREAD

**Issue by zpertee** [Azure/azure-functions-dotnet-worker#1898]
I've been going in circles for the past couple of days and I thought I'd reach out to see if there was any guidance available on my quest.  My goal is to build a single dockerized container running the isolated azure functions worker with asp.net core integration and I'd also like to self-host signalr for a couple of websocket apis.  This container then gets deployed to a number of different hosting environments including azure web app and an isolated on-premise network.  The need for the latter is why I'm trying to avoid azure signalr.  However, I'm not sure if functions can work with self-hosted signalr and I also seem to have issues in properly constructing the hostbuilder instance to get everything glued together properly.  I also considered just building an asp.net core app, but I have a heavy reliance on durable functions.  I could envision how to do this with multiple docker containers and some sort of reverse proxy, but that tends to get a little bit confusing as compared to having a single container that we can bring up or down as needed.  Any input is greatly appreciated.

**Comment by mattchenderson** [comment]
Hi - the support provided by the SignalR extension is geared toward the Azure SignalR Service. You could certainly connect to self-hosted SignalR, but the lifecycle of your function invocations could lead to the connection being terminated. Since you are building a docker image, you would be able to ensure that the worker process is fully daemonized, and your SignalR integration could potentially be set up as a service, but the function would not trigger based on SignalR activity itself.
