### ISSUE TITLE
Signal to .net worker shutdown is about to occur

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-dotnet-worker#192]
Need to improve the shutdown scenario.

Currently, it's a proces.kill: https://github.com/Azure/azure-functions-host/blob/69e70a87bad28453bae43715c1e7a5ee8893cf37/src/WebJobs.Script/Workers/ProcessManagement/WorkerProcess.cs#L204

**Comment by fabiocav** [comment]
I'm thinking we need to prioritize this work in the host. This may cause a lot of unexpected issues.

**Comment by stap123** [comment]
Is there currently any way to know that the function is being shutdown so we can do something to clean up etc?

**Comment by surgupta-msft** [comment]
Host will send a [WorkerTerminate](https://github.com/Azure/azure-functions-language-worker-protobuf/blob/58b3dc0dbde065b15bd979bd2e27f36b7ee6273e/src/proto/FunctionRpc.proto#L39) message to worker to allow the worker to terminate itself gracefully instead of immediately killing it. Worker to act on this signal and send Success response to Host.

Related issue on Host side - https://github.com/Azure/azure-functions-host/issues/2308
