### ISSUE TITLE
Kafka Extension doesn't work by missing native library

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-dotnet-worker#194]
Kafka Extension includes native library, However, it is not included

```
[2021-02-26T23:19:03.776Z] A host error has occurred during startup operation '8a691aa4-5df3-455d-afb4-5a70f9197ba8'.
[2021-02-26T23:19:03.778Z] Confluent.Kafka: Failed to load the librdkafka native library.
[2021-02-26T23:19:03.781Z] Stopping JobHost
Value cannot be null. (Parameter 'provider')
```
bin\output\.azurefunctions

![image](https://user-images.githubusercontent.com/1390976/109365721-b4206d80-7846-11eb-9f68-e497fc5144fb.png)

It should be include runtime directory.

![image](https://user-images.githubusercontent.com/1390976/109365761-cbf7f180-7846-11eb-86e0-7703db9834a9.png)

**Comment by ankitkumarr** [comment]
Adding some details from our investigation offline -- 

We all looked into this, and it seems to be caused because the "WebJobs Extensions" package that we build for the Host is targeting .NET Standard right now ([code](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/sdk/Sdk/ExtensionsCsprojGenerator.cs#L57)). And dontet standard doesn't compile the native runtime dependencies.

We talked about changing that to `netcoreapp3.1`. Though that will add a dependency of .NET Core 3 SDK to be present on users machine, we think it's an OK short term solution. We will look into other options in the future.
As part of this, we could also include a fallback build flag, so if users don't have these bindings that require native dependencies, maybe we can build `netstandard2.0` to avoid that dependency.
