### ISSUE TITLE
At-most-once delivery observed using CosmosDBTrigger 

### ISSUE THREAD

**Issue by jkbim** [Azure/azure-functions-dotnet-worker#2009]
The CosmosDBTrigger seems to be checkpointing the lease before it even hits the user code of the function.

This used to be done after the user code in the function had completed either with success or throwing and exception that would then be discarded by the trigger.

Old trigger:
```
try
	callUserFunction()
catch ex
	// Discard ex
finally
	checkpoint()
```
	
New isolated trigger:
```
checkpoint()
try
	callUserFunction()
catch ex
	// Discard ex	
```

Even if i do a FailFast in the callUserFunction() it won't save me from moving forward in the changefeed. Some completetly random error somewhere else in the code can crash my worker and the CosmosDBTrigger happily runs moving the changefeed forward again as the host restarts the worker.

Basically i can't use the CosmosDBTrigger for anything where i need reliable at-least-once messaging.

I would suggest something like what is done in the service bus trigger where you have message actions and ability to disable autocomplete. You could pass in a object allowing the user to call a checkpoint function and be responsible for the behavior.

Right now it should be a big red flag in the documentation that this trigger is behaving like its at-most-once delivery and works like Receive-and-Delete mode for Azure Service Bus.

Having a dependency injection error can also be cause the changefeed to be iterated and checkpointed even though nothing is ever processed. It do seem to be safe to throw an exception in the constructor as that just causes the function to fail without side effects to the changefeed.

```
    public class CosmosDbFunction
    {
        public CosmosDbFunction(DepInjectMistakeOrConfigError failing)
        {
                // Spins out of control and moves the changefeed along without ever processing anything. 
        }

        public CosmosDbFunction()
        {
            // Safe, just fails without changefeed moving.
            throw new Exception("Some mistake");
        }

        [Function("Function3")]
        public void Run([CosmosDBTrigger(
            databaseName: "Test",
            containerName: "Test",
            Connection = "CosmosDb",
            LeaseContainerName = "leases",
            CreateLeaseContainerIfNotExists = true, StartFromBeginning = true)] IReadOnlyList<MyDocument> input)
        {
            // Do Something
        }
    }
```

Is there some workaround with the new function middleware that can help alleviate some of these issues and bring reliable messaging.

**Comment by kshyju** [comment]
@ealsur

**Comment by ealsur** [comment]
Thanks for the feedback, will try to answer each point separately.

> The CosmosDBTrigger seems to be checkpointing the lease before it even hits the user code of the function.

This is not possible. The checkpoint happens after the Function code executes.

Reference:

https://github.com/Azure/azure-webjobs-sdk-extensions/blob/a6c80c74de3354bcb573b080d0076296e52b0b5a/src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerListener.cs#L222-L236

Once the Function Runtime Executor finishes, then and only then, we proceed to checkpoint.

What could happen though is that you have code that is not correctly following an async pattern, for example, if I have an `async` method and I don't `await` it, then the code will spawn that `Task` and do a "fire and forget" pattern. The provided code in the example is a `public void Run`, if there is any async code inside not being awaited, it could be the root of the problem.

> Some completetly random error somewhere else in the code can crash my worker and the CosmosDBTrigger happily runs moving the changefeed forward again as the host restarts the worker.

This is documented and by design: https://learn.microsoft.com/azure/cosmos-db/nosql/troubleshoot-changefeed-functions

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/1633401/aa271fe7-1dd0-4781-b2cd-89aaf806ecae)

You can define [retry policies](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages#retries) like with any other Function Trigger that supports them, to have the batch of changes be retried, but by design, event based triggers, including Cosmos DB, will move forward on unhandled errors.

> You could pass in a object allowing the user to call a checkpoint function and be responsible for the behavior.

The challenge with this is cross-language functions. A Function Trigger Attribute definition, cannot have things like lambdas or objects declared, these attributes need to be able to be set in any language (NodeJS, Python, Powershell, .NET, Java, etc) so you cannot have a type that is a .NET Func or a .NET type.

> Basically i can't use the CosmosDBTrigger for anything where i need reliable at-least-once messaging.

The Trigger guarantees at-least-once. Not only-once. Even on situations where you are not experiencing errors, you can still experience a batch being processed by multiple instances in expected scenarios (such as increasing instances and load balancing, or instance crashing and recovering), and that again is by design. This also applies to, for example, Event Hub Trigger. You need to account for the possibility of multiple deliveries of the same batch/document as part of the code design.

> Right now it should be a big red flag in the documentation that this trigger is behaving like its at-most-once delivery and works like Receive-and-Delete mode for Azure Service Bus.

This is the default behavior, like I mentioned, you can customize this using Retry Policies, which are available for multiple Function Triggers (including Cosmos DB).

**Comment by jkbim** [comment]
Hi Matias, Thank you for the speedy and thorough reply.

Not to be pedantic, and i might be mistaken, but i tried creating a CosmosDbTrigger with some long processing, 3 steps of 5 seconds. I then created a TimerTrigger which would run every 2 second and fail after some time by throwing an exception in a async void method crashing the whole app.

This would result in the CosmosTrigger only processing the first 2 steps(say 2/3 of a batch) crash, and retry the worker process but having moved the changefeed forward so the last step was lost due to some completely unrelated error elsewhere in the code.

Its a toy example and it don't happen that often that a app crashing bug makes it to production, but i would feel more at ease with better control of when checkpointing happened knowing i would not miss updates and having to bother with replaying them or detecting misses.

So i would still suggest something akin to the ServiceBusMessageActions used in the ServiceBusTrigger if its possible to implement.

**Comment by ealsur** [comment]
@jkbim You are describing what I believe is a scenario for when the process crashes, and it might be related to https://github.com/Azure/azure-webjobs-sdk-extensions/pull/870

I am not an expert on the Worker side of things, but the DrainMode might be what is coming into play here. @kshyju can you confirm?

If that is the case, maybe the above PR helps in the crashing scenario (this was a correctness fix that was requested specifically for this scenario).

**Comment by jviau** [comment]
@jkbim did @ealsur 's latest comment address your concern?
