### ISSUE TITLE
.NET 6 Isolated Functions: Unable to edit App Files with Web Deploy

### ISSUE THREAD

**Issue by thomaspb88** [Azure/azure-functions-dotnet-worker#2080]
I'm unable to edit app files for a .NET 6 Isolated Azure Function.
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/50802657/a28327c8-4d89-40e4-8561-68cf0bdbb327)

**Configurations**

App
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/50802657/ead56fbe-b142-4a55-b96b-c02ac01a73e0)

Function
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/50802657/758388ae-c191-4d8f-807c-2d11731bdf1e)

General
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/50802657/36adc193-ac1b-4cc1-9fd1-3187ec8a897c)

**Comment by kshyju** [comment]
This is by design. As the message suggests, please edit your files in your local machine using your favorite editor. Once you are done, publish the output of your app and deploy that artifacts. Remember, you are not deploying the source code, but the publish output of that (result of `dotnet publish`).
