### ISSUE TITLE
Using ASP.NET Core integration prevent appsettings.json files to be read

### ISSUE THREAD

**Issue by jcoqueret** [Azure/azure-functions-dotnet-worker#2271]
### Description

I updated a function to .NET 8 and migrated it to use the ASP.NET Core integration.
When deploying, my appsettings.json and appsettings.{env}.json are no longer loaded and all configuration from theses files are ignored.

To make it works, I had to set manually the BasePath. 
```csharp
.ConfigureAppConfiguration((hostBuilderContext, builder) =>
{
      builder.SetBasePath(Directory.GetCurrentDirectory());
})
```

```xml
<PackageVersion Include="Microsoft.Azure.Functions.Worker" Version="1.21.0" />
<PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
<PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.2.1" />
<PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.0" />
<PackageVersion Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.4" />
```

I expected to get the configuration loaded as it is part of the Host.CreateDefaultBuilder.

```csharp
private static async Task Main(string[] args)
{
     var host = Host.CreateDefaultBuilder()
	.ConfigureFunctionsWebApplication(builder =>
	{
	     builder.UseMiddleware<ExceptionLoggerMiddleware>();
	})
	.ConfigureAppConfiguration((hostBuilderContext, builder) =>
	{
	     builder.SetBasePath(Directory.GetCurrentDirectory());
	})
	.ConfigureServices(services =>
	{
        ...
	})
	.Build();
     await host.RunAsync().ConfigureAwait(false);
}
```

### Steps to reproduce

To reproduce, use the code mentioned in that ticket. Running on local does not reproduce the problem. Deploying on Azure on a Linux consumption plan does.

**Comment by philpsc** [comment]
Thanks @jcoqueret for posting this, we faced the same issue and your workaround works perfectly.

To narrow it down a bit, some of our function apps are still on .NET 6 with _Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore v1.1.1_ and show the same behavior after adding the Asp.NET Core integration.

```
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.EventHubs" Version="5.4.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.4" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk.Analyzers" Version="1.2.1" />
```

**Comment by kshyju** [comment]
> Running on local does not reproduce the problem. Deploying on Azure on a Linux consumption plan does.

@jcoqueret Could you inspect the publish payload used for the deployment to ensure these files are present with the output binaries? What was your deployment method? Does another deployment method works? Does it work when you deploy to Windows consumption?

**Comment by jcoqueret** [comment]
@kshyju my appsettings.{env}.json files are correctly deployed. I used the ZipDeploy method through Rider.
I wrote an easy Http function to list all files present in the function and the settings files are there.

I'll to deploy that function to an Windows consumption plan before the end of the week and I'll give you feed back.

**Comment by jcoqueret** [comment]
I tested it with a Windows consumption plan, and to to make it work, I had to set the `WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED` to `0`.
Without changing this setting, the function's current directory does not contain the complete set of function files (binaries, settings files, ...) so it makes sense for the configuration to fail to load. On Linux all my files are there, so I would expect to have the configuration loaded.

**Comment by ClementGermain** [comment]
I'm having the same issue on a linux based Azure Function (works fine on a Windows plan). Configuration from appsettings.json is not loaded. 

I tried multiple setup, using a new `HostBuilder` or `CreateDefaultBuilder`, using  `builderSetBasePath(Directory.GetCurrentDirectory())` or `builder.SetBasePath(context.HostingEnvironment.ContentRootPath)` etc.

I can confirm the `appsettings.json` is deployed (I can see it in the Azure Function App Files).

More info here: 
https://stackoverflow.com/questions/78119200/appsettings-for-azurefunction-on-net-8-isolated/78120434

Is there a known workaround?

Thanks

**Comment by ClementGermain** [comment]
Finally managed to get it working by adding this logic
```
if (context.HostingEnvironment.IsDevelopment() == false)
   builder.SetBasePath("/home/site/wwwroot");
```

The application files (DLLs + `appsettings.json`) are deployed under `"/home/site/wwwroot"` BUT `context.HostingEnvironment.ContentRootPath` resolves to `"/azure-functions-host"` which contains the DLLs and `appsettings.json` of the Function Host (not the application itself). So `appsettings.json` was resolved to `{"IncludeScopes":false,"LogLevel":{"Default":"Warning"}}`

`Directory.GetCurrentDirectory()` resolves to `"/tmp/functions\\standby\\wwwroot"` which isn't helpful.

This is fine on windows but apparently off for Linux. To be honest, I'm not a fan of the solution, but I can't think of anything else for now.

**Comment by fabiocav** [comment]
Discussed this issue in triage. Changes to the .NET host will likely be needed to make sure the path is correctly mapped.

**Comment by kshyju** [comment]
@jcoqueret Appreciate your patience. As you figured out, having the incorrect content root is the cause for the issue.  As you figured out, the current mitigation is to call the `SetBasePath` explicitly so that when the json files are searched for adding as config source, it is properly located. We plan to release a permanent fix to address the issue.

>  Running on local does not reproduce the problem.

I am curious about this. Were you running it locally using a container?  In theory and based on my own testing to repro this locally with a linux container (using the dockerfile generated by VS when you create a new function app), this should not work locally as well. Could you provide more details about how you were testing? If it was using container, can you provide a minimal repro (With the docker file) and share with me ? A link to GH repo would be great.

**Comment by mliotinoca** [comment]
> Finally managed to get it working by adding this logic
> 
> ```
> if (context.HostingEnvironment.IsDevelopment() == false)
>    builder.SetBasePath("/home/site/wwwroot");
> ```
> 
> The application files (DLLs + `appsettings.json`) are deployed under `"/home/site/wwwroot"` BUT `context.HostingEnvironment.ContentRootPath` resolves to `"/azure-functions-host"` which contains the DLLs and `appsettings.json` of the Function Host (not the application itself). So `appsettings.json` was resolved to `{"IncludeScopes":false,"LogLevel":{"Default":"Warning"}}`
> 
> `Directory.GetCurrentDirectory()` resolves to `"/tmp/functions\\standby\\wwwroot"` which isn't helpful.
> 
> This is fine on windows but apparently off for Linux. To be honest, I'm not a fan of the solution, but I can't think of anything else for now.

I solved it without adding logic to the code, but by configuring this environment variable directly on the Azure Function:

`DOTNET_CONTENTROOT: "/home/site/wwwroot"`

**Comment by pavel-smiatanin** [comment]
I implemented a workaround and got func app working on Linux. First of all I think it is bad idea to rely on internal MS implementation logic (as suggested above) because it can be changed later and everything will stop working. For that reason to set env variables DOTNET_CONTENTROOT to a specific folder or use hardcoded pathes should not be used at all. Moreover it did not work in my case. To understand it more clearly we should refer to tight/loose coupling types and best practices. 

What I did
- I changed properties of _appsetting.json_ and other config files and pointed them as _embedded resources_. On my environments I use env variables to override settings from file as one of approach suggested by best practices. I do not use _appsettings.prod.json_ or so.
- I implemented an extention logic to read json from the assembly resources and add it to configuration. There are 2 ways. The 1st is to implement your own configuration source. The 2nd is to implement _Microsoft.Extensions.FileProviders.IFileProvider_ & _Microsoft.Extensions.FileProviders.IFileProvider_ which deal with memory/resource assemblies and register resources by means of ext method _AddJsonFile(this IConfigurationBuilder builder, IFileProvider? provider, string path, bool optional, bool reloadOnChange)_ from _Microsoft.Extensions.Configuration.Json_ NuGet package. The 2nd is much easier.

In this case developers deal with appsetting.json file as usually. Some of them who is not aware of the problem will not see any difference if they need to add a new or change an existing setting in file and use it in code. The only thing is config file is part of assembly.. not output directory. So the same logic work in Azure function based on any OS and locally. As next step I will wait for fixing the issue by MS and replace config registration afterwards. But meanwhile I will work as I work usually.

Hope my approach will help you. If you need more info or code snippets just let me know
