### ISSUE TITLE
Azure Function app not starting using .NET 8 Isolated in China North 3 region

### ISSUE THREAD

**Issue by pilarodriguez** [Azure/azure-functions-dotnet-worker#2299]
### Description

We have a function app deployed in "China North 3" region and it has stopped working after upgrading to .Net 8. 
It was fine if we downgrade to .Net 7 or if we deploy to a different region (East US, West Europe or Southeast Asia). We are using premium service plan

Deployment is successful, but the functions are not listed. I don't see any error in the eventlog file. When I try to access the function app url I get a 503 error"
```HTTP Error 503. The service is unavailable.```

I've updated the packages to the latest version, but I get same problem
Microsoft.Azure.Functions.Worker Version="1.21.0"
Microsoft.Azure.Functions.Worker.Sdk Version="1.17.0"

### Steps to reproduce

I was able to reproduce it by creating a new .Net 8 isolated project in VS with a single hhtp trigger function. I build and deploy using yaml and provision the resources using bicep
Deploying that project to for example West Europe, works fine. But if I deploy to China North 3, it doesn't work. It also works fine in China North 3 if I downgrade to .Net 7

**Comment by kshyju** [comment]
@pilarodriguez 

1. What specific error are you getting? Do you see any errors in your app insights tables? 
2. Did you try the "Diagnose and solve problems" blade in azure portal to see if you can find more information about the failure? 
3. If you try another deployment method, the app works?

**Comment by pilarodriguez** [comment]
1. I don't get any errors. Application Insights is empty.
2. "Diagnose and solve problems" blade is disabled. That feature is not available in Azure China portal
3. I've tried deploying with yaml using `AzureFunctionApp` task and `AzureRmWebAppDeployment`. I get the same result with both

We are using durable functions. When the function app is started, it should create some tables and blobs that are used internally by the durable functions. But those are not created. It looks like the function is not starting at all

**Comment by jonatansoderberg** [comment]
**Regerding the issue with the ".NET version" setting**

This finding applies to both web applications and functions running on Windows.

A recent configuration quirk has emerged with the setup of .NET applications in China, specifically affecting the managedRuntimeVersion in the applicationhost.config file. This setting is critical for dictating the .NET Framework version an application uses, especially important for legacy ASP.NET applications not targeting .NET Core or the newer unified .NET platform.

**Key Points:**
ASP.NET V3.5 uses "v2.0".
Post-ASP.NET V3.5 applications (including .NET 6/7) default to "v4.0".
Anomaly in China: For .NET 8 applications, the managedRuntimeVersion is mistakenly set to "v8.0", a non-existent version causing IIS to fail with event id 2294 (The worker process failed to pre-load .Net Runtime version).

**Implications and Workarounds:**
This configuration error, specific to China, prevents IIS from starting properly for .NET 8 applications due to the unrecognized runtime version. Interestingly, this issue doesn't affect newer .NET platforms as managedRuntimeVersion isn’t used there.

A workaround involves setting an earlier .NET version (like .NET 6 or 7) for deployments in China to bypass the startup error. Meanwhile, in regions like Sweden Central, setting managedRuntimeVersion to v4.0 for .NET 8 applications avoids this issue entirely, indicating a region-specific bug rather than a broader compatibility problem.
.NET 8 runtime is installed in China and web applications and functions seems to run fine using that version.

**Conclusion:**
This incident highlights the critical role of correct configuration settings and how regional differences can impact the deployment of .NET applications. Addressing this bug is essential for seamless application performance across all regions, with a temporary shift to earlier .NET versions serving as a viable stopgap for those affected.

**Comment by pilarodriguez** [comment]
@kshyju Where should I create the support ticket?

**Comment by liliankasem** [comment]
@pilarodriguez you should be able to create a ticket via the portal using the "Support + Troubleshooting" tab in your Function App

**Comment by kshyju** [comment]
Please open a ticket as suggested and the team will be happy to investigate.

**Comment by willyt150** [comment]
@pilarodriguez was MS/Azure China able to resolve your issue via the support ticket? And if so was it anything on your side or something on theirs?

We're running into similar issue with getting 503 once we deploy our .NET 8 isolated functions, and these functions work just fine in Azure Global

**Comment by willyt150** [comment]
Can disregard my comment. We've figured out that our issue is configuration related.
