### ISSUE TITLE
WorkerExtensions.csproj : Target framework is set to .Net6 Even if functions are configured to target Net8 

### ISSUE THREAD

**Issue by mahrezTaharboucht** [Azure/azure-functions-dotnet-worker#2302]
### Description

We tried to migrate our Azure functions from .net6 to .net8 but we discovered that the autogenerated project "WorkerExtensions" is always targeting .net6.
Is it possible to change the target framework to .Net8 ?

Involved source code :
[https://github.com/Azure/azure-functions-dotnet-worker/blob/main/sdk/Sdk/ExtensionsCsprojGenerator.cs](https://github.com/Azure/azure-functions-vs-build-sdk/issues/url)
ligne (63)

### Steps to reproduce

- Create a .net 8 Azure function (isolated process).
- Build the function in an AzureDevops pipeline using the "UseDotNet@2" task to setup the .net8 runtime in the temp build directory. (the build agent should not have Net6 or Net8 installed globally)  
- The pipeline should fail when trying to build the WorkerExtensions project.

**Comment by kshyju** [comment]
The build/publish output of the auto generated WorkerExtensions project is indirectly used by the functions host runtime. As of today, the V4 runtime is built on .NET6. This means, we need to make sure that your build/CI environment has .NET6, so that it can build & produce the binaries which are compatible with the host runtime.

A few new improvements are coming to this area in the near future, which will allow you to remove this .NET6 requirement. No ETA to share at this point though.
