### ISSUE TITLE
.NET 8 isolated - The gRPC channel URI 'http://:' could not be parsed

### ISSUE THREAD

**Issue by alvipeo** [Azure/azure-functions-dotnet-worker#2303]
### Description

Service Bus triggered function simply doesn't work. Please see the repo - https://github.com/alvipeo/FuncAppDotnet8Iso.

### Steps to reproduce

https://github.com/alvipeo/FuncAppDotnet8Iso

This is created as a new Azure Function project and selecting Service Bus as trigger. Then it's published to Azure Function (Linux).
And ...Blow!

**Comment by kshyju** [comment]
@alvipeo Could you take a look at this - https://github.com/Azure/azure-functions-dotnet-worker/issues/2248#issuecomment-1921847568 ? What is the host version you see for your failing app?

**Comment by alvipeo** [comment]
@kshyju Thanks, the [workaround](https://github.com/Azure/azure-functions-dotnet-worker/issues/2121#issuecomment-1847281008) helped me!

I wonder if I should close the issue now..?

**Comment by alvipeo** [comment]
But then I have to set the `WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED` to `0` every single time when I deploy the project...

**Comment by kshyju** [comment]
@alvipeo As mentioned in the linked issue, the fix is in the functions host(runtime) and will be included in version 4.30.0, which is still being deployed for Linux SKU. The deployment make take a few days to complete on all regions (world wide). Let us know if you still experience the issue after your app is on 4.30.0 (You should be able to see the version in the overview blade in azure portal).

> But then I have to set the WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED to 0 every single time when I deploy the project...

No the app settings stays between deployments, unless your deployment is doing something extra to cleanup the app settings everytime.

**Comment by SWarnberg** [comment]
How about when the function is containerized in Linux and hosted in Container Apps? I get this same exception when using version 5.20.0.
