### ISSUE TITLE
The target framework 'net8.0' must be 'net6.0'. Verify if target framework has been overridden by a global property.

### ISSUE THREAD

**Issue by milen-denev** [Azure/azure-functions-dotnet-worker#2316]
### Description

That's all that I have to say. Really I am not going to specify what how. I am using latest version of whatever as of today. Congutulations, this is the 4th time I get screwed up then trying to make an publish / update my Azure functions. There are no excuses. The experience with Azure Functions is just horrible. If I get any charge I am going to immediately request refund even if it's 1 penny. 

### Steps to reproduce

Manage Dependencies -> Updates -> Select All Packges -> Update -> Get screwed for 4th time.

**Comment by davidpeden3** [comment]
i just ran into this as well. you need to roll back `Microsoft.Azure.Functions.Worker.Sdk` to whatever version you were using _prior to_ `1.17.2`. that's the version that has the bug you reported. see https://github.com/Azure/azure-functions-dotnet-worker/issues/2291 for context.

**Comment by kshyju** [comment]
@milen-denev Would you mind elaborating the issues you are running into? Are you getting error when building locally or when building in a CI environment? Do you have .NET6 installed in your build environment? That is required for building/publishing .NET Isolated function applications. 

Our goal is to ensure developers have the best experience building .NET Isolated function apps. Please provide details of the issues you are encountering, and we will promptly assist in resolving them.

**Comment by milen-denev** [comment]
The error is on my local envicoment and not withing a CI/CD. Also a screenshot of my VS Configuration: 
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/36803782/83d40459-4169-44f1-bdbd-26863276a5f9)
Is this enough? Or I have to select additional options or maybe even dowload the .net 6 SDK from the dotnet website? Who knows what is screwed.

**Comment by kshyju** [comment]
@milen-denev You need to ensure you have the SDK installed in your build environment. Can you run `dotnet --list-sdks` command in a terminal and share what you see?

**Comment by milen-denev** [comment]
I really wonder, I remember until yerstarday, that if someone wanted to build apps with certain .NET version then all you had to do is to select it in the VS Installer. So after Microsoft Edge throwing out of memory and not working, now VS uninstalls SDKs and the CSHTML editor doesn't work?

**Comment by aherrick** [comment]
i'm seeing this too in GH actions latest Nuget packages. lol

**Comment by aherrick** [comment]
rolling back to 1.71.1 fixes it. what gives? what's the fix?

**Comment by milen-denev** [comment]
> rolling back to 1.71.1 fixes it. what gives? what's the fix? cc @milen-denev

I don't know what's the fix is and I haven't fixed my issue, I just postpopned the release. But you know what I am reoppening this since I am not the only one and since it's occuring in Github Action. Pleace @aherrick give us more details. Enlighten us with the bugs. Maybe it will be fix in 2028 for windows and in 2037 for linux. Who knows

**Comment by kshyju** [comment]
I had no trouble using GH action to build a .NET Isolated function app which uses 1.17.2 Worker.Sdk package. See the action run here https://github.com/kshyju/FunctionApp44/actions/runs/8157715362. See my workflow file [here](https://github.com/kshyju/FunctionApp44/blob/master/.github/workflows/dotnet.yml).

**Comment by nicolashemery** [comment]
Hello,

I have the same issue on my computer i try to publish. I use VS 2022 (latest version) and windows 10 (latest version).
I runned the command `dotnet --list-sdks` and i have the following:
3.1.426 [C:\Program Files\dotnet\sdk]
5.0.214 [C:\Program Files\dotnet\sdk]
5.0.303 [C:\Program Files\dotnet\sdk]
5.0.403 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.321 [C:\Program Files\dotnet\sdk]
6.0.402 [C:\Program Files\dotnet\sdk]
6.0.419 [C:\Program Files\dotnet\sdk]
8.0.200 [C:\Program Files\dotnet\sdk]

**Comment by silvioboehme** [comment]
Same problem here, after update to 1.17.2:
The target framework 'net8.0' must be 'net6.0'. Verify if target framework has been overridden by a global property.
This error is not a build error. Build just works fine!
This error comes from publish!

Project setting:
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
</PropertyGroup>

Rolling back to 1.17.1 works fine.

**Comment by the-programmer** [comment]
Also the same issue here.

If I upgrade to 1.17.2, compilation results in the error `The target framework 'net8.0' must be 'net6.0'.`

Since I am compiling for an Azure function that uses .NET 8 (LTS) in the isolated worker model on Windows, rolling back to .
NET 6 is not posible.

**Comment by MikeWhalenIII** [comment]
Same issue when upgrading Microsoft.Azure.Functions.Worker.Sdk to 1.17.2. Rolling back to 1.17.1 fixes the issue.

`The target framework 'net8.0' must be 'net6.0'. Verify if target framework has been overridden by a global property. ..\WorkerExtensions.csproj`

**Comment by DrGriff** [comment]
[Shyju Krishnankutty](https://github.com/kshyju) said that he had no issue building it.

> no trouble using GH action to build a .NET Isolated function app which use

The problem is not when buiding it, it's when publishing it.

**Comment by curia-damiano** [comment]
+1

1.17.2 gives me this error
1.17.1 is ok and can publish correctly

**Comment by kshyju** [comment]
> [Shyju Krishnankutty](https://github.com/kshyju) said that he had no issue building it.
> 
> > no trouble using GH action to build a .NET Isolated function app which use
> 
> The problem is not when buiding it, it's when publishing it.

The GH action I linked above is doing a dotnet publish. See the artifacts produced on [that GH action](https://github.com/kshyju/FunctionApp44/actions/runs/8157715362). It is the output of[dotnet publish command](https://github.com/kshyju/FunctionApp44/blob/028fab60420a6bfb5b9015e12ccd377e31a6db81/.github/workflows/dotnet.yml#L23).

**Comment by FHRunner** [comment]
I observed the same thing as other recent contributors.  I had upgraded my Function project from .NET 6 to 8.  As part of that work, I upgraded Microsoft.Azure.Functions.Worker.Sdk to the very latest version, 1.17.2.  I was able to build the Function in VS 2022 and run it locally.  When I tried publishing it to Azure, the publish failed.  I then downgraded Microsoft.Azure.Functions.Worker.Sdk to 1.17.1 and now I can publish just fine.  So, this seems to be a bug in 1.17.2.

**Comment by kshyju** [comment]
@FHRunner Can you still repro the issue after doing a `dotnet clean` and then using `dotnet publish -c release -o ./youroutputfolder` to publish the output of your function app project?

**Comment by FHRunner** [comment]
When I use dotnet publish, I do not experience the failure.  Only when I publish with Visual Studio do I get the failure.  I don't fully understand the inner project thing you described.  Why must it be net6.0?  I want to upgrade my function app to .NET 8 and I want to continue to be able to publish it to Azure with Visual Studio.  Is that going to be possible with Microsoft.Azure.Functions.Worker.Sdk 1.17.2 or am I going to have to stick with 1.17.1 for now?  It seems like the latter.

**Comment by the-programmer** [comment]
For a different issue I just made a demo project to validate that the issue was solved with the latest versions (it was). But when using `Microsoft.Azure.Functions.Worker.Sdk` version 1.17.2 everything worked fine.

However this demo project has 1 difference when compared to the main solution I work in. Here there is only 1 project instead of multiple (class library) projects.

Could that be the difference we ware looking for?

**Comment by silvioboehme** [comment]
And by the way.....if you make a fresh installation of VS2022 on Windows 11 there is no .net 6 sdk installed.

**Comment by curia-damiano** [comment]
I totally agree with @silvioboehme  and all the others having this issue.
It must be something different, because even in my case, I just upgraded my project (btw a single csproj without other class libraries) and I had this issue when publishing (not when compiling and debugging locally).
And finding this GH issue, I've downgraded to 1.17.1 and the issue is gone.

I can provide my simple project so that you can try youself to publish on your tenant.

**Comment by silvioboehme** [comment]
It's a really BAD idea, to roll back a change from Oct 4, 2023 without any changes or checks and break all running functions on a LTS .net 8 version!

**Comment by mikegoatly** [comment]
@kshyju I might be able to help you reproduce this. 

* Create a new isolated function app targeting .net 8
* Do a right-click publish to create a new publish profile for an Azure Function app, using the pubxml option
* Publish the project - this should work
* Change from publishing in Release mode to Debug mode:
   <img width="245" alt="image" src="https://github.com/Azure/azure-functions-dotnet-worker/assets/4577868/420d5776-bb43-49c2-ab99-9ce28f13dfd9">
   <img width="318" alt="image" src="https://github.com/Azure/azure-functions-dotnet-worker/assets/4577868/74c0f8b9-fa96-461f-99ab-598048a57be1">
* Publish the project again - you'll get the error "The target framework 'net8.0' must be 'net6.0'" in the output window

I think the issue stems from the publish profile getting the following elements added:

```xml
    <TargetFramework>net8.0</TargetFramework>
    <SelfContained>false</SelfContained>
    <SkipExtraFilesOnServer>true</SkipExtraFilesOnServer>
```

Removing the `TargetFramework` from the pubxml file allows the publish to work again.

**Comment by kshyju** [comment]
Thanks @mikegoatly Yea, the VS publish profile updating the TargetFramework was discussed before [here](https://github.com/Azure/azure-functions-dotnet-worker/issues/1995#issuecomment-1861852883).  We will continue to follow up on that issue (That issue is closed as the SDK changes to support that was done. but that caused another regression (in 1.17.0 and 1.17.1) and we had to revert that (in 1.17.2). We will revisit that issue again.

**Comment by dajbych** [comment]
I experienced this error as well, but it was caused by moving the resource to a different Resource Group.

**Comment by dajbych** [comment]
I got this error too. Deleting the line in the file `{appName} - Zip Deploy.pubxml` containing `<TargetFramework>net8.0</TargetFramework>` helped me solve it.

**Comment by codeputer** [comment]
another day trying to solve this issue - able to do a dotnetpublish - but fails to deliver it to my Azure Function running a Linux plan.   Is there another way to upload files to LInux?  I only spent 2 days on this, which I gave an estimate for an hour... argh.

**Comment by mellevsen** [comment]
I started getting this error too since upgrading to 1.17.2 yesterday.

Rolling back to 1.17.1 fixed it.

Thank goodness I found this post.

**Comment by kyurkchyan** [comment]
I have started this issue after upgrading to `1.17.2`. Downgrading to `1.17.1` resolves the issue.

**Comment by codeputer** [comment]
Bugs like this took me forever to find, cost me hundreds as I had to move to a windows app plan (as it worked without this problem), before finally downgrading and getting it too work again.  Makes me really think the upgrade of packages is dangerous, and something you should not do until you really  need to.

**Comment by atsmark** [comment]
I recreated the publishing setup in VS and it fixed the problem.

**Comment by martonx** [comment]
On gitlab, docker based build, we run this: dotnet publish -c Release -f net8.0 -r linux-x64 --no-self-contained
You can easily reproduce the error.
On local everything works fine.
Shame on you guys.

**Comment by lionelschiepers** [comment]
Hi, 

I have the same problem. My build works locally but it fails on azure devops. I have on both environments a global.json that globally sets the .NET framework 8 => the build is probably not the cause of the problem otherwise it should fail locally too.

on azure devops, I'm dogin a publish with these parameters: "--configuration Release -r linux-x64 -p:PublishReadyToRun=true".

=> There is perhaps a regression with 1.17.2 with some kind of publish on .NET 8 at least.

This bug exist since more than 23 days and many people seems to have the problem. If durable function is the future, it would be much than appreciated that a regression like this one is solved quickly.

In the mean time, I've downgraded to 1.17.0 because 1.17.2 seems to be a revert of a change in 1.17.1

**Comment by lionelschiepers** [comment]
I works when I remove "-r linux-x64 -p:PublishReadyToRun=true" in my build pipeline during the publish. BTW it must work in all configuration and this regression must be solved.

**Comment by raysuelzer** [comment]
Having this issue as well deploying to win-x86

**Comment by gwise-vision** [comment]
Same Issue.
"The target framework 'net8.0' must be 'net6.0'. Verify if target framework has been overridden by a global property."
Microsoft.Azure.Functions.Worker.Sdk - 1.17.2
There will be no problem if you downgrade to version 1.17.1.

Does the MS development team only do local testing? An error occurs when publishing to Azure server.

**Comment by CaidenKehrer** [comment]
Same issues here. Do we have any update as to when an update will come out that fixes this issue? I had to roll back all of my projects to 1.17.1.

**Comment by tacoWanneeJama** [comment]
> I got this error too. Deleting the line in the file `{appName} - Zip Deploy.pubxml` containing `<TargetFramework>net8.0</TargetFramework>` helped me solve it.

This worked for me. So for now I would say this is the easiest solution.

**Comment by atbez-miview** [comment]
FYI.  Updating from 1.17.2 to 1.17.3-preview fixed this specific issue for me locally, but caused a different issue in Azure Devops where the WorkerExtensions.csproj was trying to restore from my private repo and failing.

**Comment by doruksro** [comment]
> Taky jsem dostal tuto chybu. Smazání řádku v souboru `{appName} - Zip Deploy.pubxml`obsahujícím `<TargetFramework>net8.0</TargetFramework>`mi to pomohlo vyřešit.

Hurray works, thank you for all, one day lost with this problem. I am search in my disk file global.json, that never used. Already 3 days lost for transfer from In-process to Isolated Model. And later 1 day more to delete 1 line.

**Comment by jviau** [comment]
> The target framework 'net8.0' must be 'net6.0'. Verify if target framework has been overridden by a global property.

That error message is there to intentionally turn a runtime failure into a compile time failure. The inner build _must_ be built with same TFM that the functions runtime is (in this case .NET6). For a while it was possible to override this inner builds TFM to .NET8 via global properties (a common way was via VS pubxml). Doing so can lead to runtime assembly load failures. In `1.17.0` we added two things:

1. Preventing the global property from flowing (fixing the issue)
2. Adding a safeguard in case it is somehow overridden still. (to avoid obscure runtime failures)

In `1.17.2` we reverted number 1, but left 2 in place. With `1.17.3-preview1` number 1 is back in place.

As for the nuget restore change, this was also an intentional bug fix where the inner build was not inheriting nuget sources from outer build, effectively blocking any usage of extensions on feeds other than nuget.org. If these feeds are private you will need to add an authentication step before building the function app.

**Comment by raysuelzer** [comment]
So we should be using .net 6 for functions?

**Comment by jviau** [comment]
> So we should be using .net 6 for functions?

You may use net8.0. Just be aware that If you are not using the `1.17.3-preview1` you may encounter this issue. The fix is typically to remove whatever is setting that global TFM property. In the case of publishing from VS, delete the `<TargetFramework>net8.0</TargetFramework>` line from your `.pubxml`

**Comment by jviau** [comment]
This is resolved by #2347

**Comment by jviau** [comment]
@ulluoink it is available here https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.17.3-preview1

We resolve issues when the code change is merged in.

**Comment by Bit-Shifts** [comment]
I came across this issue as well and updating to [1.17.3-preview1] solved it.

**Comment by ulluoink** [comment]
preview is absolutely no option in production

**Comment by Bit-Shifts** [comment]
You are not wrong when it comes to good practices.

**Comment by Emeka-MSFT** [comment]
> Bugs like this took me forever to find, cost me hundreds as I had to move to a windows app plan (as it worked without this problem), before finally downgrading and getting it too work again. Makes me really think the upgrade of packages is dangerous, and something you should not do until you really need to.


> _Makes me really think the upgrade of packages is dangerous, and something you should not do until you really need to._

The inability to upgrade dependencies is a security issue. Azure Functions need to address this.  You stated that: _"something you should not do until you really need to."_ I disagree. By the time you are forced to upgrade, you'll be met with a wider set of breaking changes, inexplicable errors (such as in the current github issue), and thus expanded scope of work. If the motivation is to address a security concern, then you mitigation steps (i.e. by upgrading) introducing additional ambiguity. 

Summary:
It seems like every few months this particular (set of) Azure function package(s) results in some form of random error, resulting in upgrade/downgrade workaround. This is a security issue and should be addressed by design. The ability to upgrade dependencies, and thus stay within the latest/supported version is a priority-0 feature. 

Azure Functions team need to revisit their design of this random csproj generation feature (which seems to create a single class, with a single method...). IMO, a bad, hacky design.

**Comment by Emeka-MSFT** [comment]
> > The target framework 'net8.0' must be 'net6.0'. Verify if target framework has been overridden by a global property.
> 
> That error message is there to intentionally turn a runtime failure into a compile time failure. The inner build _must_ be built with same TFM that the functions runtime is (in this case .NET6). For a while it was possible to override this inner builds TFM to .NET8 via global properties (a common way was via VS pubxml). Doing so can lead to runtime assembly load failures. In `1.17.0` we added two things:
> 
> 1. Preventing the global property from flowing (fixing the issue)
> 2. Adding a safeguard in case it is somehow overridden still. (to avoid obscure runtime failures)
> 
> In `1.17.2` we reverted number 1, but left 2 in place. With `1.17.3-preview1` number 1 is back in place.
> 
> As for the nuget restore change, this was also an intentional bug fix where the inner build was not inheriting nuget sources from outer build, effectively blocking any usage of extensions on feeds other than nuget.org. If these feeds are private you will need to add an authentication step before building the function app.

I think that the fundamental problem is the use of dynamic code generation. This moves static code analysis/validation to the runtime phase. As a result, simple incompatibility issues that the compiler could/would very easily catch, would be missed. Azure function need to re-evaluate the cost benefit ratio of adopting and implementing dynamic dependencies. 

My take, Azure function team should provide a method that each consumer would call IFF they need the feature, whatever that feature is. Azure function should move away from attempting to "dynamically" add such call, whatever they are. 

So many devs, over the years, have lost time, dealing with this stupid design. Azure Function team, please fix it. No more workarounds.

**Comment by PhilWheat** [comment]
1.17.2 is still marked as latest and still has the issue.

**Comment by OlufTE** [comment]
@jviau Great, that you've solved this issue. Do you know when the fix is expected to be released? I am in the middle of migrating a larger code base to the isolated worker model, and it is an issue that there is no released version of the SDK that actually works (earlier versions have other issues).

**Comment by chassq** [comment]
Hey @jviau. Is there any ETA on when this will be released? We have need of this fix as well. We just ran into this today. Glad we came across this post as we had no clue what was happening when we tried to publish.

**Comment by OlufTE** [comment]
@chassq It seems like it has been released now. There is a version 1.17.3 that was released 3 days ago, and a version 1.17.4 that was released yesterday.

**Comment by chassq** [comment]
I see it now. Thank you!

**Comment by davidfordaus** [comment]
> i just ran into this as well. you need to roll back `Microsoft.Azure.Functions.Worker.Sdk` to whatever version you were using _prior to_ `1.17.2`. that's the version that has the bug you reported. see #2291 for context.

Or roll forward rather than backward.  This issue isn't present in 1.17.4 and immediately fixes the issue.   What automated DevOps-style testing processes are used during the release process (if anyone is aware of it from a Microsoft standpoint).
