### ISSUE TITLE
Declare the projects as alpha and non production ready due to being riddled with bugs.

### ISSUE THREAD

**Issue by milen-denev** [Azure/azure-functions-dotnet-worker#2340]
This is a must so people are aware that the projects and nuget packages that correspond to this GitHub repo are non production ready and are in alpha or pre alpha stage with a complete list of known issues and workarounds if any for those who want to risk using this.

**Comment by fabiocav** [comment]
We sincerely appreciate the engagement and the feedback, but the approach in this issue is not constructive.

We regret the issues you've experienced with the recent SDK releases, and the team has been working diligently on responding to your issues and addressing them with updates. But this repo contains source used to produce a large set of packages, and your experience with the SDK does not reflect their quality state.

We take quality seriously, and the version you've been impacted by was indeed in preview for additional customer validation, but unfortunately, a set of scenarios were still impacted. We're taking steps to ensure this doesn't happen again.

The team has been graciously interacting with you, and I ask you to please reflect and reconsider how you approach engagement with them in an open repository.

If there is more information you would like to share directly, please feel free to reach out to me at fabio.cavalcante@microsoft.com.
