### ISSUE TITLE
AI logs are not flushed when process exits

### ISSUE THREAD

**Issue by dmytro-gokun** [Azure/azure-functions-dotnet-worker#2379]
### Description

We have a .NET 8 function app (isolated). When the app starts we register this lifetime callbacks:

```
    public static IHost InitializeLogging(this IHost @this)
    {
        var logger = @this.Services.GetRequiredService<ILogger<ApplicationLog>>();
        var lifetime = @this.Services.GetRequiredService<IHostApplicationLifetime>();
        lifetime.ApplicationStarted.Register(() => logger.LogInformation("Application started"));
        lifetime.ApplicationStopping.Register(() => logger.LogInformation("Application stopping"));
        lifetime.ApplicationStopped.Register(() => logger.LogInformation("Application stopped"));
        return @this;
    }

```

In this application we also have configured Application Insights logging using services.AddApplicationInsightsTelemetryWorkerService()/services.ConfigureFunctionsApplicationInsights().

All in all, logging works just fine and we get all our log in AI. "Application started" is getting to AI as well. But we never get "Application stopping"/"Application stopped" in AI. My assumption is that the function app exits before those message are actually transmitted to AI server. Is this correct? Is there any way to fix this behavior?

### Steps to reproduce

1. Create an Azure Function app.
2. Add Application insights logging.
3. Log lifetime events
4. Deploy Function app to Azure and run it.
5. Make sure its stopped.
6. Examine AI logs.

**Comment by dmytro-gokun** [comment]
@liliankasem I've done some additional testing and i can confirm that ApplicationStopping & ApplicationStopped events are fired indeed. So the problem (most likely) is in some events not reaching AI indeed.  I think, we need some fix for this

**Comment by dmytro-gokun** [comment]
Is there any chance this gets worked on any time soon?

**Comment by RohitRanjanMS** [comment]
Hi @dmytro-gokun I reviewed the AppInsights logs, and I see that the telemetry skink was disposed before `lifetime.ApplicationStopped` event occurred. Since [ApplicationStopped](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostapplicationlifetime?view=net-8.0#:~:text=Triggered%20when%20the%20application%20host%20has%20performed%20a%20graceful%20shutdown.) is supposed to be triggered when the host has performed a graceful shutdown. So the behavior seems as expected.

```
2024-09-11T22:51:45.1969101Z:{e6e8119f-dc04-4455-a5ba-de1517ce7557}{System.Object[]}{System.Diagnostics.Tracing.EventPayload}{0}
2024-09-11T22:51:45.1969147Z:Ignoring event written from EventSource: {0} as no counters from this event source are configured to be collected.{Microsoft-ApplicationInsights-Data}{FunctionApp}
2024-09-11T22:51:45.1969804Z:Process was called on the TelemetrySink after it was disposed, the telemetry data was dropped.{FunctionApp}
```

**Comment by dmytro-gokun** [comment]
@RohitRanjanMS But i did not Dispose it. All i have in this app is "stock" Microsoft code. Do not you think it should work as expected out of the box? I do not understand why you closed the issue. Nothing has been fixed.

**Comment by dmytro-gokun** [comment]
@liliankasem Why this got closed? It has not been fixed

**Comment by RohitRanjanMS** [comment]
During the application shutdown process, .NET disposes of services that are registered with the dependency injection container. Since the ApplicationStopped event is often triggered too late (after services have already been disposed), it's advisable to log critical shutdown events in the ApplicationStopping event instead. The behavior you've observed is expected; the Application Insights telemetry sink, as part of the logging infrastructure, is typically disposed of when the application is stopping.

**Comment by dmytro-gokun** [comment]
@RohitRanjanMS > it's advisable to log critical shutdown events in the ApplicationStopping event instead

But  logs ApplicationStopping do not come to AI as well. That is a problem, is not it?

**Comment by RohitRanjanMS** [comment]
Hi @dmytro-gokun, I was able to get my logs from the `ApplicationStopping` event but I acknowledge that there's no way to reliably get these logs as `ApplicationLifetime` is not tied to how services are disposed.

Can you elaborate your scenario?

**Comment by dmytro-gokun** [comment]
@RohitRanjanMS The scenario is that we are trying to troubleshoot function timeouts in production. For that we are doing some logging, but those logs do not end up in AI as the app exits before the latest log events are flushed. So, not only the logging statement from ApplicationStopping is lost, but all some prior messages as well (few seconds/minutes)

**Comment by RohitRanjanMS** [comment]
Hi @dmytro-gokun , there's something going on otherwise you shouldn't miss logs prior logs. You have full control over the worker process and the dependency injection. I will suggest you write the diagnostic events coming from AppInsights SDK to a storage (or to a file if running locally) and see what's happening with the AppInsights SDK. 

See a reference implementation here - https://github.com/Azure/azure-webjobs-sdk/blob/3309c1c57ea1e207772fcbb066d88f588ab8a1c0/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/SelfDiagnostics/ApplicationInsightsEventListener.cs#L26

**Comment by dmytro-gokun** [comment]
@RohitRanjanMS In my first comment in this thread i've posted reproduction steps. Have you tried them? Are you able to get 'stopping' entry in AI reliably?

**Comment by RohitRanjanMS** [comment]
yes, I tried the code locally and I do see the log from the `stopping` most of the time.

**Comment by dmytro-gokun** [comment]
@RohitRanjanMS Try running it on Azure. Also, "most of the time" is not a reliable result. It should always be there, right? We are computer people, we want computers do their thing in a reliable manner, not "most of the time".

**Comment by dmytro-gokun** [comment]
@RohitRanjanMS And? Have you tried running it on Azure?
