### ISSUE TITLE
Serialization setting JsonUnmappedMemberHandling.Disallow resulting in timed trigger attributes not serializing anymore

### ISSUE THREAD

**Issue by jcageman** [Azure/azure-functions-dotnet-worker#2384]
If i register the system.text.json serialization settings as below the attribute serialization of at least timed triggers break. Is this a bug or somewhere documented what is supported? You can see the serialization issue described with the relevant code below. I am using the latest worker nugets

```
    public static JsonSerializerOptions CreateDefaultSerializerOptions()
    {
        return new JsonSerializerOptions
        {
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
            NumberHandling = JsonNumberHandling.Strict,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
            Converters = { new JsonStringEnumConverter(allowIntegerValues: false) }
        };
    }
    
    public static async Task Main(string[] args)
    {
        var host = new HostBuilder()
            .ConfigureFunctionsWorkerDefaults(builder =>
            {
                builder.Serializer = new JsonObjectSerializer(CreateDefaultSerializerOptions());
            })
            .Build();
        await host.RunAsync();
    }
```

```
public class MyTimerTrigger
{
    private readonly ILogger<MyTimerTrigger> _logger;

    public MyTimerTrigger(
        ILogger<MyTimerTrigger> logger)
    {
        _logger = logger;
    }

    [Function(nameof(MyTimerTrigger))]
    public async Task RunAsync(
        [TimerTrigger("0 */5 * * * *")] TimerInfo myTimer)
    {
            _logger.LogInformation(
                "{FunctionName} result at {Date}
                nameof(MyTimerTrigger), DateTime.Now);
    }
}

```

Relevant error logging:

```LOG
Executed 'Functions.MyTimerTrigger' (Failed, Id=80952193-3ed8-40d9-9dbc-6d284eb5ecb9, Duration=239ms)
[2024-02-12T08:47:07.062Z] System.Private.CoreLib: Exception while executing function: Functions.MyTimerTrigger. System.Private.CoreLib: Result: Failure
Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'MyTimerTrigger': Cannot convert input parameter 'myTimer' to type 'Microsoft.Azure.Functions.Worker.TimerInfo' from type 'System.String'. Error:System.Text.Json.JsonException: The JSON property 'Schedule' could not be mapped to any .NET member contained in type 'Microsoft.Azure.Functions.Worker.TimerInfo'.
```

**Comment by liliankasem** [comment]
Hi @jcageman - I copied the code you shared above and was not able to repro the issue, the timer trigger is executing successfully for me. Can you share a full code repro project where this issue is happening?

Here is what I tried:

Program.cs
```csharp
        static async Task Main(string[] args)
        {
            var host = new HostBuilder()
                .ConfigureFunctionsWebApplication()
                .ConfigureServices(services =>
                {
                    services.AddApplicationInsightsTelemetryWorkerService();
                    services.ConfigureFunctionsApplicationInsights();
                })
                .ConfigureFunctionsWorkerDefaults(builder =>
                {
                    builder.Serializer = new JsonObjectSerializer(CreateDefaultSerializerOptions());
                })
                .Build();

            host.Run();
        }

        public static JsonSerializerOptions CreateDefaultSerializerOptions()
        {
            return new JsonSerializerOptions
            {
                DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
                NumberHandling = JsonNumberHandling.Strict,
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
                Converters = { new JsonStringEnumConverter(allowIntegerValues: false) }
            };
        }
```

Timer Function:
```csharp
        [Function(nameof(MyTimerTrigger))]
        public async Task RunAsync([TimerTrigger("0 */1 * * * *", RunOnStartup=true)] TimerInfo myTimer)
        {
            _logger.LogInformation("{FunctionName} result at {Date}", nameof(MyTimerTrigger), DateTime.Now);
        }
```

Output:
```log
[2024-04-09T21:23:00.001Z] Executing 'Functions.MyTimerTrigger' (Reason='Timer fired at 2024-04-09T14:23:00.0013510-07:00', Id=c82ee4c9-4016-4623-a809-1ab929973eb6)
[2024-04-09T21:23:00.003Z] Executed 'Functions.MyTimerTrigger' (Succeeded, Id=c82ee4c9-4016-4623-a809-1ab929973eb6, Duration=2ms)
```

You can try using this approach for serialization config instead:

https://github.com/Azure/azure-functions-dotnet-worker/blob/de334081abb1038c14e84153f11214ad7bf037cb/samples/Configuration/Program.cs#L39-L50

Ultimately, our converters use the serializer from worker options, so if you override all defaults (the way you are in your example) you could be breaking your application. If you do this, you may need to ensure that this is set:

https://github.com/Azure/azure-functions-dotnet-worker/blob/de334081abb1038c14e84153f11214ad7bf037cb/src/DotNetWorker/Hosting/ServiceCollectionExtensions.cs#L35

**Comment by jcageman** [comment]
Can reproduce it when i remove `".ConfigureFunctionsWebApplication()"` from the default function app.

**Comment by liliankasem** [comment]
Gotcha; removing `ConfigureFunctionsWebApplication` worked and was able to repro the issue. It's interesting that with the WebApplication config the issue goes away.

This should be fully supported so we will need to investigate why `UnmappedMemberHandling` specifically breaks the converters.

**Comment by liliankasem** [comment]
It looks like the reason you're getting this specific error:

`Cannot convert input parameter 'myTimer' to type 'Microsoft.Azure.Functions.Worker.TimerInfo' from type 'System.String'. Error:System.Text.Json.JsonException: The JSON property 'Schedule' could not be mapped to any .NET member contained in type 'Microsoft.Azure.Functions.Worker.TimerInfo'.`

is because the [TimerInfo](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.Timer/src/TimerInfo.cs) object in the timer extension does not include a "Schedule" property. By setting `UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow`, this breaks the conversion.

To address this, we will implement a converter for this type that does not user customer serialization, that issue can be tracked here:

- https://github.com/Azure/azure-functions-dotnet-worker/issues/2411

As for why adding `ConfigureFunctionsWebApplication` fixes the issue, this is probably a bug with "ConfigureFunctionsWebApplication" - the behaviour should not differ and the scenario you describe you should also break with "ConfigureFunctionsWebApplication". The bug could be that we are not properly registering customer serialization when `builder.Serializer` is used. We will be using this issue to track and address that bug:

- https://github.com/Azure/azure-functions-dotnet-worker/issues/2403

Let me know if you have further questions; if not I will resolve this issue in favour of using the above mentioned issues to track fixes. Thanks!

**Comment by kshyju** [comment]
@jcageman https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Timer/4.3.1 is published with this change. Could you give it a try? Thanks!
