### ISSUE TITLE
Azure Storage Blob Trigger metadata properties are always missing. 

### ISSUE THREAD

**Issue by Dolphinsimon** [Azure/azure-functions-dotnet-worker#2388]
### Description

A very simple blob trigger function:
```csharp
[Function(nameof(ProcessMessages))]
public async Task ProcessMessages([BlobTrigger("messages/{name}", Connection = "BlobEndpoint")] byte[] blob,
    string name,string blobTrigger,Uri uri, IDictionary<string, string> metadata, BlobProperties properties)
{}
```
From the document: [Metadata](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cextensionv5&pivots=programming-language-csharp#metadata) the metadata parameters should be passed the information of the blob, all the other parameters passed the right information, only the 'BlobProperties properties' is initialized without data.

### Steps to reproduce

```csharp
using Azure.Storage.Blobs.Models;
using Microsoft.Azure.Functions.Worker;

namespace BlockFunctionApp
public class BlobFunction
{
[Function(nameof(ProcessMessages))]
public async Task ProcessMessages([BlobTrigger("messages/{name}", Connection = "BlobEndpoint")] byte[] blob,
    string name,string blobTrigger,Uri uri, IDictionary<string, string> metadata, BlobProperties properties)
{}
}
```

**Comment by kshyju** [comment]
It seems you're utilizing the `Azure.Storage.Blobs.Models.BlobProperties` type from the Azure.Storage.Blobs assembly. [This type](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/Extensions/Blob/BlobTriggerBindingSamples.cs) is designed to be immutable, meaning its properties cannot be modified after creation. Additionally, its constructors are marked as internal, limiting their accessibility outside of the assembly where they are defined. Due to these design choices, the binding pipeline in the dotnet isolated worker, which presumably operates in a different assembly or context, is unable to bind directly to this type.

To work around this limitation, you have a couple of options:

1. Use a different parameter type: Instead of `Azure.Storage.Blobs.Models.BlobProperties`, you can use a different type for the "properties" parameter. For instance, you could use `string` type to receive a JSON string representing the blob properties. This allows you to still access the relevant data without directly binding to the `BlobProperties` type.

2. Create a custom POCO (Plain Old CLR Object): Another option is to define your own minimal class that contains only the properties you're interested in from the `BlobProperties` type. This custom class can then be used as the parameter type, allowing you to bind to it directly within the binding pipeline.

```csharp
public sealed class BlobItemProperties
{
    public DateTimeOffset LastModified { get; set; }

    public DateTimeOffset CreatedOn { get; set; }

    public long ContentLength { get; set; }

    public string ContentType { get; set; }

    public byte[] ContentHash { get; set; }
}
```
and

```csharp
[Function("ProcessMessages")]
public async Task Run([BlobTrigger("messages/{name}", Connection = "BlobEndpoint")] Stream stream,
    string name,
    BlobItemProperties properties
    )
{
    using var blobStreamReader = new StreamReader(stream);
    var content = await blobStreamReader.ReadToEndAsync();
    _logger.LogInformation($"C# Blob trigger function Processed blob\n Name: {name} \n Data: {content}");
}
```

Hope this helps. Please let us know if you still have questions.

**Comment by gha-zund** [comment]
> It seems you're utilizing the `Azure.Storage.Blobs.Models.BlobProperties` type from the Azure.Storage.Blobs assembly. [This type](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/Extensions/Blob/BlobTriggerBindingSamples.cs) is designed to be immutable, meaning its properties cannot be modified after creation. Additionally, its constructors are marked as internal, limiting their accessibility outside of the assembly where they are defined. Due to these design choices, the binding pipeline in the dotnet isolated worker, which presumably operates in a different assembly or context, is unable to bind directly to this type.
> 
> To work around this limitation, you have a couple of options:
> 
> 1. Use a different parameter type: Instead of `Azure.Storage.Blobs.Models.BlobProperties`, you can use a different type for the "properties" parameter. For instance, you could use `string` type to receive a JSON string representing the blob properties. This allows you to still access the relevant data without directly binding to the `BlobProperties` type.
> 2. Create a custom POCO (Plain Old CLR Object): Another option is to define your own minimal class that contains only the properties you're interested in from the `BlobProperties` type. This custom class can then be used as the parameter type, allowing you to bind to it directly within the binding pipeline.
> 
> public sealed class BlobItemProperties
> {
>     public DateTimeOffset LastModified { get; set; }
> 
>     public DateTimeOffset CreatedOn { get; set; }
> 
>     public long ContentLength { get; set; }
> 
>     public string ContentType { get; set; }
> 
>     public byte[] ContentHash { get; set; }
> }
> and
> 
> [Function("ProcessMessages")]
> public async Task Run([BlobTrigger("messages/{name}", Connection = "BlobEndpoint")] Stream stream,
>     string name,
>     BlobItemProperties properties
>     )
> {
>     using var blobStreamReader = new StreamReader(stream);
>     var content = await blobStreamReader.ReadToEndAsync();
>     _logger.LogInformation($"C# Blob trigger function Processed blob\n Name: {name} \n Data: {content}");
> }
> Hope this helps. Please let us know if you still have questions.

This does not help for me, the object is always null.

I'm using .NET 8
Microsoft.Azure.Functions.Worker.Sdk 2.0.5
Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs 6.7.0

i'm testing at my local machine, using a real storage account in the cloud.
using function core tools 4.0.5611
