### ISSUE TITLE
.azurefunctions folder contains DLLs for in-process model despite project targeting isolated process

### ISSUE THREAD

**Issue by jkennan** [Azure/azure-functions-dotnet-worker#2460]
We build several Azure Functions projects on .NET 8, targeting the isolated process model. We typically publish and deploy on Linux systems. As a result of a recent vulnerability scan of package dependencies in our build output, we noticed that the `.azurefunctions` folder produced by build output contains DLLs such as the following, which indicate that it is including packages for the in-process model: 
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            3/1/2024 12:10 PM          24576 Microsoft.Azure.WebJobs.Extensions.FunctionMetadataLoader.dll
-a---           7/11/2023  2:43 PM          37256 Microsoft.Azure.WebJobs.Extensions.Rpc.dll
-a---           12/4/2023  1:45 PM         234528 Microsoft.Azure.WebJobs.Extensions.ServiceBus.dll
-a---           10/4/2019 10:44 AM          83832 Microsoft.Azure.WebJobs.Host.Storage.dll
-a---           7/11/2023  2:40 PM          25992 Microsoft.Azure.WebJobs.Rpc.Core.dll
```

However, we only explicitly include the Microsoft.Azure.Functions.Worker.* packages in our `.csproj` files and only target the isolated process model for our functions. 

Can you help me understand why the in-process DLLs are included, and if we can stop them from appearing in our build output?  This will limit our build and release size, and avoid scanning unnecessary packages for vulnerabilities.

Thanks!

**Comment by kshyju** [comment]
This is intentional. Each version of the worker extensions is linked to a specific version of the WebJobs extension packages, ensuring that the functions host runtime can load these packages when your function app starts. The functions host runtime continues to use the WebJobs package for the functionality of the extension.

See example [here](https://github.com/Azure/azure-functions-dotnet-worker/blob/13fdd1fe132b400d98e0f4a5e2ec10777aace7c0/extensions/Worker.Extensions.ServiceBus/src/Properties/AssemblyInfo.cs#L7C34-L7C82).

**Comment by jviau** [comment]
Closing as this is by-design.
