### ISSUE TITLE
System.Text.Json Vulnerability in WorkerExtensions.csproj

### ISSUE THREAD

**Issue by WretchedDade** [Azure/azure-functions-dotnet-worker#2593]
### Description

I am getting an alert for a vulnerable version of `System.Text.Json` being used in `WorkerExtensions.csproj`. I can see it is being flagged as it is a transitive dependency of these packages:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/17183431/6019d964-b2a0-4d92-b08d-1f8919f43fb2)

I've done quite a bit of digging but can't seem to find anywhere with a workaround to fix this since it's a second phase. Is there any way to force this project to reference the latest stable version of STJ or do I need to wait for these packages to be updated themselves? If I do need to wait, is this being tracked or worked on anywhere?

### Steps to reproduce

Build a functions app project and have it scanned by component governance in ADO.

**Comment by josesos** [comment]
My team is having the same issue. Other packages with vulnerabilities that we must update and can't because they are being referenced by the generated Release/net8.0/WorkerExtensions/WorkerExtensions.csproj are:
- Upgrade Azure.Identity from 1.10.4 to 1.11.0 to fix the vulnerability.
- Upgrade Microsoft.Identity.Client from 4.56.0 to 4.60.4 to fix the vulnerability.

Could you please provide a way for us to choose the packages versions to reference? This is a critical item for our team.

**Comment by josesos** [comment]
There is an older issue related to this. There were plans to add a feature to enable teams to add or update internal build packages, but it looks like it was dropped and then picked up again.
#2221

**Comment by MaxMommersteeg** [comment]
If you're dealing with following CVE: https://github.com/advisories/GHSA-hh2w-p6rv-4g7w

Then (I think) it should be enough to just rebuild and deploy using .NET 8.0.7 or later.

---

@josesos regarding the issue you mention. This is roughly the same issue I'm dealing with, but both vulnerabilities pop-up because I depend on `microsoft.azure.webjobs.extensions.sql (3.0.534)` somehow, referenced in WorkerExtensions.csproj. This isn't something I coded myself. In my own function app project I have a dependency on:
- `<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Sql" Version="3.0.534" />`

Which maybe translates to dependency mentioned earlier in WorkerExtensions.csproj. Couldn't find a way to resolve this just yet.

**Comment by josesos** [comment]
It was not enough for us to rebuild using .NET 8.0.7. We always use the latest .NET 8 SDK. We were able to fix the issue for other Nuget packaged we references by updating the transitive dependency version explicitly in our project, but we could not do the same for worker extensions. The system identifies this location as the issue:
![image](https://github.com/user-attachments/assets/d84bef6a-0319-4869-bb48-d3d9a32fea80)

**Comment by bradhugh** [comment]
Same issue here. Looking forward to a solution ASAP.

**Comment by fabiocav** [comment]
@WretchedDade this issue is being tracked with the appropriate teams to ensure dependencies are updated.

Security issues are not tracked prior to fixes, so those items are internal. The same applies to disclosures and the details are shared [here](https://github.com/Azure/azure-functions-dotnet-worker/security/policy). That's one of the options in the issue creation flow and the appropriate folks will be engaged when notifying of security concerns that way.

I'll close this based on what I've stated above, but we'll have updates to address the issue soon.

Thank you!
