### ISSUE TITLE
Generated WorkerExtensions.csproj under obj folder causes Component Governance issues

### ISSUE THREAD

**Issue by up2pixy** [Azure/azure-functions-dotnet-worker#2604]
### Description

This is about Microsoft.Azure.Functions.Worker.Sdk nuget.

We got some Azure DevOps Component Governance issues caused by the generated WorkerExtensions.csproj under obj folder as it has transitive nuget references of old version of System.Text.Json (CVE-2024-30105), Azure.Identity (CVE-2024-35255) and Microsoft.Identity.Client (CVE-2024-35255 and CVE-2024-27086)

Could you please update or add direct reference to mitigate the issue?

Btw, is Microsoft.Azure.Functions.Worker.Sdk really needed if we just build and deploy our isolated worker Azure Functions on Windows Azure Service Plan? Based on this article it's required but just want to double confirm. https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#core-packages 

### Steps to reproduce

1. Add the latest Microsoft.Azure.Functions.Worker.Sdk nuget to the project
2. Build using Azure DevOps pipeline
3. Check Component Governance for vulnerabilities

**Comment by up2pixy** [comment]
Related issue: #2593

**Comment by Porges** [comment]
In addition to the ones mentioned above we're seeing these two packages from the SignalR integration: `Microsoft.IdentityModel.JsonWebTokens` ([CVE-2024-21319](https://github.com/dotnet/announcements/issues/290)), `System.IdentityModel.Tokens.Jwt` ([CVE-2024-21319](https://github.com/dotnet/announcements/issues/290)).

**Comment by fabiocav** [comment]
@up2pixy this issue is being tracked with the appropriate teams to ensure dependencies are updated.

Security issues are not publicly tracked prior to fixes, so those items are internal. The same applies to disclosures and the details are shared [here](https://github.com/Azure/azure-functions-dotnet-worker/security/policy). That's one of the options in the issue creation flow and the appropriate folks will be engaged when notifying of security concerns that way.

I'll close this based on what I've stated above, but we'll have updates to address the issue soon.

Thank you!
