### ISSUE TITLE
Service Bus 'Message''s label

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-functions-dotnet-worker#284]
Since 'Message' is no longer a valid servicebus trigger option, how do you go about retrieving the attributes such as 'Label' from the input message?

This was also asked and not answered in followups to #226

**Comment by onionhammer** [comment]
Update: Looks like these properties can be retrieved through `FunctionContext`;
 `context.BindingContext.BindingData.TryGetValue("Label", out var label)`

This should be documented somewhere

**Comment by fabiocav** [comment]
Agreed.

@ggailey777 we can sync up on this and enhancements to the [FunctionContext section](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#execution-context) to cover some core scenarios (sorry, this was missing in preview 5)

**Comment by fabiocav** [comment]
@mattchenderson flagging documentation item here, though, this is also addressed with the SDK type bindings work.

**Comment by mattchenderson** [comment]
We have documentation on the [message metadata properties](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=python-v2%2Cisolated-process%2Cextensionv5&pivots=programming-language-csharp#message-metadata) that are populated and available on the FunctionContext. We probably are lacking an example of using that specifically.

The `Message` type and its `Label` property are from the now-deprecated Microsoft.Azure.ServiceBus package. I'm not 100% sure what the equivalent is for [Azure.Messaging.ServiceBus.ServiceBusReceivedMessage](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceivedmessage?view=azure-dotnet), though I think it may be `ApplicationProperties`.

You can also bind directly to `ServiceBusReceivedMessage` from the binding parameter itself, rather than going through the `FunctionContext`. That is documented here: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=python-v2%2Cisolated-process%2Cextensionv5&pivots=programming-language-csharp#usage
