### ISSUE TITLE
Is TimerInfo gone?

### ISSUE THREAD

**Issue by forki** [Azure/azure-functions-dotnet-worker#292]
https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/SampleApp/Timer/TimerFunction.cs#L21

I can't find a built in TimerInfo type? This seems very weird to have a custom CLIMutable custom type.

Any pointers to the built in one?

**Comment by brettsam** [comment]
We'll have a built-in one coming in the Timer Extension soon. Because it's pretty straightforward to do this yourself, it got punted until after GA.

But this is getting asked quite a bit, so we'll try to prioritize this (all it needs are some good tests now). We can use this issue to track that work.
