### ISSUE TITLE
Allow Trigger attributes on method

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-dotnet-worker#314]
For something like `[TimerTrigger]` -- the parameter that gets passed in isn't really required. I suspect a decent number of people never even use it. It could clean things up a little to allow you to specify `[TimerTrigger]` at the method level, and leave the parameter off of your method completely.

**Comment by kinetiq** [comment]
Couple thoughts here:

- Adding a second way to achieve the same result increases complexity; it will result in devs needing to understand why there are two paths to the same result. The benefits would need to outweigh this cost. 

- It is a fact that this parameter is rarely used. However, if I suddenly need more control, having the parameter present gives me a chance to succeed without additional research. If I had instead used this method level attribute and I needed more power, I would be at a dead end and I might stay there for awhile depending on how good your documentation gets. 

- If this is driven by the developer confusion around the "bring your own parameter" approach I discovered in the samples, my two cents is that the parameter itself is not the problem. The problem is the additional concepts surrounding internal model binding. Please do not try to solve that by introducing complexity in a different area.  If that isn't the driving force then disregard. :)

Thanks for all the hard work!

**Comment by brettsam** [comment]
This is stale... I don't think this is something we'd ever tackle without re-thinking all of the attributes, etc.
