### ISSUE TITLE
Uploading files via HTTP Trigger/Multipart FormData

### ISSUE THREAD

**Issue by JasonTFifer** [Azure/azure-functions-dotnet-worker#322]
Can someone give some guidance on how to upload files to the new .NET 5 functions? This was pretty straightforward before, but I'm not having much luck now with the new HttpRequestData object. Or can someone provide information on how to upload a file and JSON data in the same request? If this isn't doable right now, I'm going to have to spin up a .NET Core 3.1 function to strictly handle file uploads, which I'm hoping I don't have to do.

**Comment by fabiocav** [comment]
We could provide some guidance, but honestly, it's a cumbersome process. 

Flagging this so we can work on implementing a proper set of APIs for this.

**Comment by JasonTFifer** [comment]
I appreciate your response and look forward to when this is available. I decided to go with .NET Core 3.1 for any file uploads for now. Thank you!

**Comment by MarcAnnous** [comment]
Hi @fabiocav I see from #366 that this one is being pushed. I am at a point where I cannot go back to .NET Core 3.1. Would you still be able to give the guidance even if the process is cumbersome? Thanks for your help.

**Comment by Slagethor** [comment]
Hi there,

I'm not sure about handling them on .NET 5 but maybe that runtime has become less relevant for those reading this in the meantime. In any case, I got the handling of form data working on localhost for a .NET 8.0 isolated app by implementing what's in [this article](https://learn.microsoft.com/en-gb/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#aspnet-core-integration).

The main take-away of the article is that you need to implement `.ConfigureFunctionsWebApplication()` instead of the regular functions host builder extension call. For this to work you need to add the packages mentioned in the article. Once that is done, you can swap `HttpRequestData` for `HttpRequest` in your function signature and use the `Request.Form`  property to access the deserialized form data and process it further.

**Comment by fabiocav** [comment]
@JasonTFifer we're going through some older issues and this was still open.

With the [ASP.NET Core integration](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#aspnet-core-integration), you should be able to handle this similar to the way you would in ASP.NET Core (same set of APIs).

**Comment by JasonTFifer** [comment]
@fabiocav I admittedly haven't done much with Functions lately. I'll need to brush up on all the new goodness. Thanks for your response.
