### ISSUE TITLE
TimerTrigger needs regulary manual action

### ISSUE THREAD

**Issue by trueleader** [Azure/azure-functions-dotnet-worker#345]
We deployed .Net 5 Azure Functions in the **rgTicketTrackingToolGP01** resource group of the **gategrouphq** tenant. 
The Function app **TTToolFunctions** is running in **West Europe** on **Windows** with a **consumption plan**

There is a TimerTrigger **SendReminders** which should be triggered each 15 minutes. 
But after a few times it stops fireing. The trigger fires again a few times if we restart the Function app or manually trigger the function from VisualStudioCode:
![image](https://user-images.githubusercontent.com/7026107/112133672-37c24580-8bcc-11eb-94f7-91bd9ba811f0.png)
There are some more events now because we tested the application

May it be, because we use the general object type instead a concrete POCO type for the TimerInfo? It shouldn´t because we don´t use it inside the method:
```csharp
	public class TimerJobs
	{
		private readonly ITicketService _service;

		public TimerJobs(ITicketService service) => _service = service;

		[Function(nameof(SendReminders))]
		public async Task SendReminders(
			[TimerTrigger("0 */15 * * * *") /* each 15 minutes */] object timer /* we only need the attribute */)
		{
			await _service.SendOpenReminders().ConfigureAwait(true);
		}
	}
```

**Comment by trueleader** [comment]
**TTToolFunctions**
I tried to post each relevant information in the first part of the body :)

I did not found much inside the logs of the Function-App host. They end with "Executed 'Functions.SendReminders' ..." and thats it

**Comment by djjlewis** [comment]
I have recently deployed functions with timer triggers and also notice they just stop firing. Weirdly, as soon as I go to the portal to check and click around / refresh they seem to start back up again!

For example, this function should be running every 30 minutes, but I can see it stopped this afternoon and hasn't run since:

![image](https://user-images.githubusercontent.com/6518665/112210029-15531b00-8c12-11eb-9633-7e64253d437a.png)

We're also running on a consumption plan and the function name is `studytravel-mm-functions-qa`

**Comment by trueleader** [comment]
Any news here?

**Comment by trueleader** [comment]
Someone started the function manually as I wrote the last comment (maybe it was me and I can´t remember). All events from then till now have fired.
Maybe the plattform was updated? Seems to work now :)
