### ISSUE TITLE
Unable to add/remove users to/from groups in signalR

### ISSUE THREAD

**Issue by arashcomsense** [Azure/azure-functions-dotnet-worker#347]
Apparently the examples illustrated [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service-output?tabs=csharp#send-to-a-group) are no longer working to add or remove users to signalR groups. Where can we find some .NET 5.0 examples to help understand how to manage users groups in signalR and send messages to groups.

[This example ](https://github.com/anthonychu/azure-functions-dotnet5-signalr-sample/issues/1)did not provide such details.

**Comment by fabiocav** [comment]
@anthonychu has this changed significantly? We seem to be getting a lot of questions around SignalR here, so it would be good to see if we can work on a more substantial sample and documentation

**Comment by arashcomsense** [comment]
@anthonychu The following code snippet is similar to our working one in .netcoreapp3.1. What would be the equivalent of it in .net5.0 as it's producing compile error which was expected. Is there a document to lead us to put something working together?

```csharp
public static class AddToGroup
	{
		[Function("addtogroup")]
		public static Task Run(
			[HttpTrigger(AuthorizationLevel.Function, "get", Route = "addtogroup/{customerKey}/{userId}")]
 			HttpRequestData req,
			string tenantId,
			string userId,
			[SignalR(HubName = "testhub")]
 			IAsyncCollector<SignalRGroupAction> signalRGroupActions,
			FunctionContext executionContext)
		{
			return signalRGroupActions.AddAsync(new SignalRGroupAction
			{
				UserId = $"{tenantId}_{userId}",
				GroupName = tenantId,
				Action = GroupAction.Add
			});
		}
	}
```

**Comment by arashcomsense** [comment]
@fabiocav @anthonychu Any updates on this question?

**Comment by anthonychu** [comment]
See this example for using the output binding: https://github.com/anthonychu/azure-functions-dotnet5-signalr-sample/blob/main/Messages.cs

**Comment by arashcomsense** [comment]
@anthonychu I already saw that example but that did not answer my question! 
How can one add a user to a messaging group or remove a user from a messaging group in signalR? Let me elaborate it with a scenario like the code snippet in [this comment](https://github.com/Azure/azure-functions-dotnet-worker/issues/347#issuecomment-805972861): 

- We have an app with multiple tenants. Each tenant has a bunch of users and we want to send out a message to the users of a particular tenant. How can this goal be achieved in .net 5.0? At some point, one of the users logs out and we need to remove him/her from the group. How can it be done too?

Apparently, a dynamic object is returned per your example:

```cs
return new 
{
    Target = "newMessage",
    Arguments = new object[] { message }
}
```

What are the implications of the fields that should exist in the returned dynamic object? Where are they documented/explained to be able to make sense out of them? How should `Target` field be initialized to accommodate sending a message to a group if that field is supposed to take care of it?

/cc @fabiocav

**Comment by ak37165** [comment]
It seems from the sample code at [https://github.com/anthonychu/azure-functions-dotnet5-signalr-sample/blob/main/Messages.cs](https://github.com/anthonychu/azure-functions-dotnet5-signalr-sample/blob/main/Messages.cs) that it only returns the signalR response but not the response to the Http request. Not sure if that is valid. Wish the documentation was clearer on that aspect.

Rather, I used multiple output bindings as explained here: [https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#multiple-output-bindings](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#multiple-output-bindings)

The code is largely based on snippets from [https://github.com/Azure/azure-functions-dotnet-worker/issues/294](https://github.com/Azure/azure-functions-dotnet-worker/issues/294):

So we first define a class for multiple output bindings:

`public class MySignalROutput
        {
            [SignalROutput(HubName = "chat", ConnectionStringSetting = "AzureSignalRConnectionString")]
            public List<object> Notifications { get; set; } = new List<object>();

            public HttpResponseData Response { get; set; }
        }`

Then, the function to add can be defined as an HttpTrigger:

`[Function("AddToGroup")]
        public static MySignalROutput AddToGroup(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "addtogroup/{groupid}/{connectionid}")] HttpRequestData req,
            string groupid, string connectionid, FunctionContext executionContext)
        {
            var output = new MySignalROutput();            

            output.Notifications.Add(
                new SignalRGroupAction
                {        
                    connectionId = connectionid,
                    groupName = groupid,
                    action = "add"
                });

            output.Response = req.CreateResponse(HttpStatusCode.OK);
            return output;
        }`

Removing from group is similar. Have tested in .Net5.0 that it works.

NOTE 1: You need to provide either connectionId or userId for adding to the group. The above snippet uses connectionId. And of course add the nuget package Microsoft.Azure.Functions.Worker.Extensions.SignalRService.

NOTE 2: Seems the SignalR triggers sample here [https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/Extensions/SignalR](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/Extensions/SignalR) would only work with Hub-based SignalR services and not serverless ones - though I could be wrong since Azure functions are likely intended for people interested in serverless computing.

**Comment by yg-endava** [comment]
Thanks, @ak37165 this works. Only for **removeAll** couldn't make it work. 

When I try to remove a user from all groups like this:

```
[Function("UnsubscribeAllGroups")]
public SignalRResponse UnsubscribeAllFeeds(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "unsubscribeAllGroups")] HttpRequestData httpRequest)
{
    var output = new SignalRResponse();
    output.Notifications.Add(
        new
        {
            userId = user.Id,
            action = "removeAll"
        });

    output.Response = httpRequest.CreateResponse(HttpStatusCode.OK);

    return output;
}
```

I get the following error:

> [2021-06-19T18:20:18.885Z] Executed 'Functions.UnsubscribeAllGroups' (Failed, Id=51c3fdcd-606c-4d92-a204-ba3ef04f0f6c, Duration=7ms)
[2021-06-19T18:20:18.887Z] System.Private.CoreLib: Exception while executing function: Functions.UnsubscribeAllGroups. Microsoft.Azure.WebJobs.Extensions.SignalRService: Unable to convert JObject to valid output binding type, check parameters.

**Comment by ak37165** [comment]
> Thanks, @ak37165 this works. Only for **removeAll** couldn't make it work.
> 
> When I try to remove a user from all groups like this:
> 
> ```
> [Function("UnsubscribeAllGroups")]
> public SignalRResponse UnsubscribeAllGroups(
>     [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "unsubscribeAllGroups")] HttpRequestData httpRequest)
> {
>     var output = new SignalRResponse();
>     output.Notifications.Add(
>         new
>         {
>             userId = user.Id,
>             action = "removeAll"
>         });
> 
>     output.Response = httpRequest.CreateResponse(HttpStatusCode.OK);
> 
>     return output;
> }
> ```
> 
> Which is equivalent of this for .NET Core 3.1 Function
> 
> ```
> [FunctionName("UnsubscribeAllGroups")]
> public async Task<IActionResult> UnsubscribeAllGroups(
>     [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "unsubscribeAllGroups")] HttpRequest request,
>     [SignalR(HubName = "%SignalRHubName%")] IAsyncCollector<SignalRGroupAction> signalRGroupActions)
> {
>     await signalRGroupActions.AddAsync(
>          new SignalRGroupAction
>          {
>              UserId = user.Id,
>              Action = GroupAction.RemoveAll
>          });
> 
>     return new OkResult();
> }
> ```
> 
> I get the following error:
> 
> > [2021-06-19T18:20:18.885Z] Executed 'Functions.UnsubscribeAllGroups' (Failed, Id=51c3fdcd-606c-4d92-a204-ba3ef04f0f6c, Duration=7ms)
> > [2021-06-19T18:20:18.887Z] System.Private.CoreLib: Exception while executing function: Functions.UnsubscribeAllGroups. Microsoft.Azure.WebJobs.Extensions.SignalRService: Unable to convert JObject to valid output binding type, check parameters.

Seems the JSON mapping is failing - maybe some property name is missing. It seems via a web search that at some point group name was required to be passed for removeAll (even though we are not asking the user to be removed from any specific group but all groups). Try adding the property **groupName** (with one of the group names as values, or even a random group name) to output.Notifications.Add(
        new
        {
            userId = user.Id,
            action = "removeAll"
        });

Not tried this, just guessing...

**Comment by ak37165** [comment]
@yg-endava, if you look at the definition on SignalRGroupAction in the .NetCore 3.1 function (in VS right click and select go to definition):

```
namespace Microsoft.Azure.WebJobs.Extensions.SignalRService
{
    [JsonObject]
    public class SignalRGroupAction
    {
        public SignalRGroupAction();

        [JsonProperty("connectionId")]
        public string ConnectionId { get; set; }
        [JsonProperty("userId")]
        public string UserId { get; set; }
        [JsonProperty("groupName")]
        [JsonRequired]
        public string GroupName { get; set; }
        [JsonProperty("action")]
        [JsonRequired]
        public GroupAction Action { get; set; }
    }
}
```

There is a [JsonRequired] on groupName. The removeAll functionality was added later (was not part of the original set of allowed group actions, [as this SO post shows](https://stackoverflow.com/questions/11442591/signalr-leave-all-groups)) and the developer who added that functionality probably overlooked removing [JsonRequired] from groupName.
So even though the removeAll action does not need it, the binding expects it to be present. I am guessing all that, but due to lack of proper documentation, we just need to try things out to see what works...

**Comment by arashcomsense** [comment]
@fabiocav is there a better and more out-of-the-box solution/example/pattern in .NET 6.0 to follow to be able to add/remove user groups and even negotiate?

**Comment by Y-Sindo** [comment]
I have created a PR #774 to provide some convenient POJOs for SignalR extensions, hoping that the development experience will be more friendly with that.

As for the `RemoveAll` issue, it is a bug already fixed in the in-process model, but it is not applied to isolated-process model yet. The next release of SignalR extensions for isolated-process will fix this issue.

**Comment by arashcomsense** [comment]
@Y-Sindo Are there any working examples on sending a message to a user in a group or sending a message to all users in a group? Is there a consolidated documentation that I can follow to achieve such basic goals?

**Comment by Y-Sindo** [comment]
> @Y-Sindo Are there any working examples on sending a message to a user in a group or sending a message to all users in a group? Is there a consolidated documentation that I can follow to achieve such basic goals?

@arashcomsense I have added a sample [here](https://github.com/aspnet/AzureSignalR-samples/tree/main/samples/DotnetIsolated-BidirectionChat). Please tell me if you have any other questions.

**Comment by arashcomsense** [comment]
@Y-Sindo Thanks. That's very useful.
