### ISSUE TITLE
How is uploaded files handled with new HttpRequestData vs old HttpRequest?

### ISSUE THREAD

**Issue by devlead** [Azure/azure-functions-dotnet-worker#366]
With previous versions of Azure Functions, one could handle standard HTTP put form file uploads as below

```csharp
var formdata = await req.ReadFormAsync();
var file = req.Form.Files["file"];
```

Where [Files](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.iformcollection.files?view=aspnetcore-5.0#Microsoft_AspNetCore_Http_IFormCollection_Files) property was an [IFormFileCollection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.iformfilecollection?view=aspnetcore-5.0).

How does one do that with  `HttpRequestData`?

**Comment by fabiocav** [comment]
@devlead let me work on a sample for this. This is an area where we'd potentially need some new APIs, as without them, the process might be a little cumbersome. 

I'll block some time to look at this as soon as possible.

**Comment by razfriman** [comment]
👋 Came here to ask the same thing, Might reconsider the migration this early since I need to access a file upload within my function.

Keen to see this area improve 🤞

**Comment by fabiocav** [comment]
Let me assign this to the next sprint so we can make progress on some samples and potential API plans

**Comment by piekstra** [comment]
Also came here to ask about accessing `form-data` instead of the raw `Body`. Slack "interactions" send a POST request using form data that looks like "payload=%7B%22example%22%3A1%7D". Currently having to use string manipulation on the body after stream-reading it in order to pull out the payload value.

**Comment by JamesBroadberry** [comment]
Commenting because I've also ran in to this while trying to migrate to .NET 5 - specifically with file uploads.

**Comment by JamesBroadberry** [comment]
Something that @acrov and I have found to work while Microsoft works out the best solution is to use a NuGet package called [HttpMultipartParser](https://www.nuget.org/packages/HttpMultipartParser/) ([source code](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser)) and use it like the following:

```csharp
var parsedFormBody = await MultipartFormDataParser.ParseAsync(httpRequestData.Body);
```

Doing so, you can get files and parameters easily.
See the source code of HttpMultipartParser's README for examples of how to use it

**Comment by fabiocav** [comment]
Moving to sprint 103 for initial scoping

**Comment by fabiocav** [comment]
Work in progress with scope/approach. Moving to 104 for implementation.

**Comment by fabiocav** [comment]
Hoping to have a PR out soon, but moving to 105 to reflect the actual sprint changes will be landing.

**Comment by garrynewman** [comment]
> Something that @acrov and I have found to work while Microsoft works out the best solution is to use a NuGet package called [HttpMultipartParser](https://www.nuget.org/packages/HttpMultipartParser/) ([source code](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser)) and use it like the following:
> 
> ```cs
> var parsedFormBody = await MultipartFormDataParser.ParseAsync(httpRequestData.Body);
> ```
> 
> Doing so, you can get files and parameters easily. See the source code of HttpMultipartParser's README for examples of how to use it

Running into this too - is this still what everyone is doing, or is there an official way now?

**Comment by fabiocav** [comment]
Apologies for the lack of movement on this, as this work ended up getting pushed by other tasks. Flagging this for review so we can prioritize this work.

FYI @anthonychu @kshyju

**Comment by shanerowley-ds** [comment]
Hi, this appears to be exactly what I want. I'm using Postman and adding a couple files in the Body Form-Data. But an exception is thrown every time the line is executed. I'd appreciate some help.

`await MultipartFormDataParser.ParseAsync(httpRequestData.Body)`

Using MultipartFormDataParser 5.0.0 or 5.01, the error is 
_Value cannot be null. (Parameter 'source')_
I don't know what this 'source', it seems to be unrelated to anything of my specific HttpRequest.

Using MultipartFormDataParser 5.1.0, the error is
_Unable to determine boundary: either the stream is empty or we reached the end of the stream_

I see there is some information in request header. So it looks like it's coming in from Postman. I can't seem to read the Body though `request.ReadAsStringAsync()` just gives an empty string. Don't know if this is helpful.
Content-Type: "multipart/form-data; boundary=--------------------------351093833067400603251987"
Content-Length: "403112"

**Comment by acrov** [comment]
@shanerowley-ds from the symptoms you describe this seems more likely an issue with the [MultipartFormDataParser](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser) than with azure functions dotnet worker so you'll probably get a better response if you raise a new issue (with some minimal repro code) there.

**Comment by shanerowley-ds** [comment]
Great success! Thanks, that helped a ton. Made my day. The issue was reported there a few times already. I'm feeling a little silly - wish I looked there immediately instead of the 50+ browser tabs I had opened prior trying to figure out how to upload a file.

**Comment by galadril** [comment]
Any news on this topic?

**Comment by steven-forrrest-vincit** [comment]
Is multipart form data parsing still in the works?

**Comment by Marusyk** [comment]
Well... what is the status? Any updates since 2021?

**Comment by knightfall** [comment]
bump :(

**Comment by razfriman** [comment]
Sorry Microsoft, it's been 1.5 years....

**Easy solution: switch to AWS Lambda or Google Cloud Run Functions.**

Been working like a charm for me.. 🚀

**Comment by SelviColba** [comment]
Same here

**Comment by Nachum-SolarGik** [comment]
Same here

**Comment by maximebono** [comment]
@fabiocav Any update ?

**Comment by kwacks** [comment]
Isolated functions aren't getting much love Microsoft.  Seems like we have a number of half-baked solutions with Azure functions - in proc (eol soon) and isoloated (missing features). It'd be nice to see some of these features prioritized. 
Any updates?

**Comment by fabiocav** [comment]
Folks, sincere apologies for the lack of updates on this issue. 

The team has been focused on Isolated model improvements (this is a top priority), including deeper platform and runtime changes that will address the limitations with the HTTP model and the need for the HTTP representation types used today (`HttpRequestData`, `HttpResponseData` and associated types). That work covers:

- HTTP model enhancements
  - Access to the actual HTTP request, enabling more advanced HTTP scenarios (e.g., streaming, chunking, etc.)
    - With this in place, we'll be able to expose the same model that is supported in-proc today, using ASP.NET abstractions
- Logging and observability improvements
  - Improved Application Insights integration and OTel support
- SDK Type bindings
  - Support for advanced/rich binding patterns to SDK types (e.g., `BlobClient`, `Streams`, etc.)
- Durable Functions
- Cold start and performance improvements  

The efforts above are tracked by [this epic](https://github.com/Azure/azure-functions-dotnet-worker/issues/1008) and are currently in different stages, with some of them (e.g., Durable Functions and SDK Type bindings) becoming available very soon (Durable Functions is currently in preview with most tracked items closed and the SDK Type bindings feature is nearing public preview). Additional information is also available [here](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/net-on-azure-functions-roadmap-update/ba-p/3619066)

I agree that communication needs to improve to make sure we're providing more frequent updates on those long running efforts, otherwise, the perception is that this area is not getting the attention it needs. I also realize that it is difficult to track those that work with issues and activity across the different repos. We'll be discussing actions on this in the coming week.

The items above are efforts to avoid what @kwacks mentions above with the solutions that we bring to Isolated, but favoring the right approach, as opposed to something that is _close enough_, in order to address the missing features and capabilities, does have an impact on the timelines. And that is where communication becomes critical.

With that said, features like the one tracked by this issue are important quality-of-life improvements and we should be addressing with the current model before we get to where we want to be, so I'm sorry this fell through the cracks and will once again mark this issue for implementation.

Thank you all for your patience. The team is working hard to deliver on the items above and we'll more actively share this progress as we move forward.

**Comment by fabiocav** [comment]
Wanted to share a link to the issue we'll be using to track the HTTP model enhancements: #1387 please follow that for updates.

**Comment by fabiocav** [comment]
@rodolfograve this is in the backlog, but not something we've had the capacity to address yet. We'll provide updates on this issue when progress is made here, but currently, there isn't anything to report.

**Comment by razfriman** [comment]
This is unfortunate to hear - seems like a basic use case that is missing.

I was able to resolve this issue myself by using Google or AWS Cloud offerings

**Comment by fabiocav** [comment]
@razfriman sorry to hear that as well. We're actively working on significant enhancements in this area. We do have to prioritize our efforts and, unfortunately, that does mean we aren't always able to deliver on everything as quickly as we'd like.
I do hope you give the new model we've announced a try in the future.

**Comment by Marusyk** [comment]
@fabiocav we understand but now it's mid 2023 while the issue was opened in 2021. This is a very basic functionality.  So, maybe it's time to prioritize, isn't it?

**Comment by fabiocav** [comment]
@Marusyk we go through prioritization reviews frequently, and while the age of an issue is a factor we consider, there are others that have pushed a number of other items ahead of this. It does not mean this issue isn't important, just that we had others that were assigned higher priority.

This capability is available in preview with the HTTP model enhancements we have [recently announced](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#aspnet-core-integration-preview). We'd love any feedback you can provide on this.

Thanks!

**Comment by luizs81** [comment]
People, seriously? We are getting close to 2024 and this hasn't been solved?

**Comment by briandunnington** [comment]
if you want a quick solution and dont want to use the preview bits that @fabiocav mentioned, you can do this:
```
        public static HttpContext AsHttpContext(this HttpRequestData req)
        {
            var httpContext = new DefaultHttpContext();
            httpContext.Request.Method = req.Method;
            httpContext.Request.Path = PathString.FromUriComponent(req.Url);
            httpContext.Request.Host = HostString.FromUriComponent(req.Url);
            httpContext.Request.Scheme = req.Url.Scheme;
            httpContext.Request.Query = new QueryCollection(QueryHelpers.ParseQuery(req.Query.ToString()));
            foreach (var header in req.Headers)
                httpContext.Request.Headers[header.Key] = header.Value.ToArray();
            httpContext.Request.Body = req.Body;
            return httpContext;
        }
```
then you can use `req.AsHttpContext().Request.Form` or any of the other existing form-related pieces from ASP.NET Core.

**Comment by martonx** [comment]
It is 2023 september. What is the current solution now?

**Comment by sa-es-ir** [comment]
@briandunnington Very good solution and thanks for that, I was using **HttpMultipartParser** Nuget package but for large is uses extra memory as a result of using **Microsoft.IO.RecyclableMemoryStream** library:

By using HttpMultipartParser here is the memory usage:
![Screenshot 2023-09-28 113723](https://github.com/Azure/azure-functions-dotnet-worker/assets/12181394/46a9fe37-3f94-4f68-bbf5-d47374161665)


But when I remove it and used that extension for creating httpcontext I got this:

![Screenshot 2023-09-28 122225](https://github.com/Azure/azure-functions-dotnet-worker/assets/12181394/4738a3f6-a91c-433b-b52e-60b7eed8ca54)

**Comment by svengeance** [comment]
For anyone (like me) coming across this issue on recent searches, there's an in-house solution presented at https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#aspnet-core-integration

Using this will give us access to the HttpContext we all know and love. Verified it works well on a freshly deployed isolated fn.

**Comment by fediaza** [comment]
Is there any advancement in this topic yet??

**Comment by NFCoimbra** [comment]
> Is there any advancement in this topic yet??

Yes. [Here](https://github.com/Azure/azure-functions-dotnet-worker/issues/366#issuecomment-1806514847).

**Comment by dazfuller** [comment]
Thanks for the link @svengeance it's saved me hours of pain

**Comment by fabiocav** [comment]
Closing this as the recommendation would be to use the [ASP.NET Core integration](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#aspnet-core-integration), which would enable you to use the model described in the original issue.

**Comment by EHF32** [comment]
I don't think closing this issue is appropriate at this time, as the ASP.NET Core integration does not seamlessly support the OpenAPI extensions, leading to significant issues such as blank Swagger pages and the inability to render OpenAPI documents properly. Given these unresolved compatibility issues, it would be premature to recommend ASP.NET Core integration as a solution.



https://github.com/Azure/azure-functions-openapi-extension/issues/617

**Comment by chuongmep** [comment]
Hi, can I know what is the final solution here?
