### ISSUE TITLE
Enviroment is not set on entering ConfigureAppConfiguration (.Net Isolated)

### ISSUE THREAD

**Issue by ErikDeRoos** [Azure/azure-functions-dotnet-worker#385]
The environment is still 'Production' when I enter the ConfigureAppConfiguration((context, builder) => in the HostBuilder, even when I run this locally and I am sure all environment variables are set up properly.

So the following pattern to get Development settings in doesn't work:
```csharp
builder
  .AddCommandLine(args)
  .AddJsonFile(Path.Combine(context.HostingEnvironment.ContentRootPath, "appsettings.json"), optional: true, reloadOnChange: false)
  .AddJsonFile(Path.Combine(context.HostingEnvironment.ContentRootPath, $"appsettings.{context.HostingEnvironment.EnvironmentName}.json"), optional: true, reloadOnChange: false)
  .AddEnvironmentVariables();
```

Printing out the environment variables gives "AZURE_FUNCTIONS_ENVIRONMENT Development" but the value is ignored apparently.
Adding "ASPNETCORE_ENVIRONMENT" and "DOTNET_ENVIRONMENT" to local.settings.json Values also seems to be ignored.

The documentation is not that good on it either. https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#customizing-configuration-sources references the old (non isolated) way of doing this, and if I try to implement this Startup : FunctionsStartup the IConfigurationBuilder isn't available anymore there (only IConfiguration) so it probably runs too late in the startup process.

**Comment by ErikDeRoos** [comment]
For now I am running it like this

```csharp
builder
  .AddCommandLine(args)
  .AddJsonFile(Path.Combine(context.HostingEnvironment.ContentRootPath, "appsettings.json"), optional: true, reloadOnChange: false)
  .AddJsonFile(Path.Combine(context.HostingEnvironment.ContentRootPath, $"appsettings.{context.HostingEnvironment.EnvironmentName}.json"), optional: true, reloadOnChange: false)
#if DEBUG
  .AddJsonFile(Path.Combine(context.HostingEnvironment.ContentRootPath, $"appsettings.Development.json"), optional: true, reloadOnChange: false)
#endif                        
  .AddEnvironmentVariables();

```

Dirty, but it works.

**Comment by SeanFeldman** [comment]
If you add `local.appsettings.json`, is that one picked up? With my functions, I used that file with In-proc SDK for local development.

**Comment by pherbel** [comment]
I'm also looking for a solution.

**Comment by ErikDeRoos** [comment]
@SeanFeldman All files are working as intended. AppSettings.Development.json is available in the local environment on run. That is why my temp fix does work. 

It is about context.HostingEnvironment.Environment not being set properly in the scope of ConfigureAppConfiguration.

**Comment by fabiocav** [comment]
This is unfortunately being bumped as sprint 100 is now over, but hoping to have an update on this soon.

**Comment by MarcAnnous** [comment]
The workaround wouldn't work with core tools, right?

**Comment by fabiocav** [comment]
Updating the sprint to better reflect when the work will be happening, but I'm hoping to have an update on this soon.

**Comment by rgylesbedford** [comment]
I was able to get this to work locally (didn't test in Azure) in the following situations:

**Minimal Changes:**

1. Set an env var for "DOTNET_ENVIRONMENT" to a non obvious value (e.g. "Staging")
2. Use `Host.CreateDefaultBuilder()` instead of `new HostBuilder()`
3. Verify `hostContext.HostingEnvironment.EnvironmentName` is "Staging"

``` csharp
public class Program
{
    public static async Task Main(string[] args)
    {
        var host = Host.CreateDefaultBuilder()
            .ConfigureFunctionsWorkerDefaults()
            .ConfigureAppConfiguration((hostContext, configurationBuilder) =>
            {
                var hostEnvironment = hostContext.HostingEnvironment;
                // Add Configuration Providers
            })
            .Build();

         await host.RunAsync();
    }
}
```

**Brute Force approach**

1. Set an env var for "AZURE_FUNCTIONS_ENVIRONMENT" to a non obvious value (e.g. "Staging2")
2. Use `Host.CreateDefaultBuilder()` instead of `new HostBuilder()`
3. Verify `hostContext.HostingEnvironment.EnvironmentName` is "Staging2"

``` csharp
public class Program
{
    public static async Task Main(string[] args)
    {
        var host = new HostBuilder()
            .ConfigureHostConfiguration(configurationBuilder =>
            {
                var env = Environment.GetEnvironmentVariable("AZURE_FUNCTIONS_ENVIRONMENT");

                if (!string.IsNullOrWhiteSpace(env))
                {
                    // Based on https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Hosting/src/HostingHostBuilderExtensions.cs#L28
                    configurationBuilder.AddInMemoryCollection(new[] {
                        new KeyValuePair<string, string>(HostDefaults.EnvironmentKey, env)
                    });
                }
            })
            .ConfigureFunctionsWorkerDefaults()
            .ConfigureAppConfiguration((hostContext, configurationBuilder) =>
            {
                var hostEnvironment = hostContext.HostingEnvironment;
                // Add Configuration Providers
            })
            .Build();

         await host.RunAsync();
    }
}
```

**Comment by Matthewsre** [comment]
@rgylesbedford , thanks for sharing your workaround. I am now using this approach and it has unblocked me as nothing else would allow me to set the environment. Even local.settings.json was causing the error I encountered here:

https://github.com/Azure/azure-functions-core-tools/issues/2465#issuecomment-851728655

**Comment by fabiocav** [comment]
Quick update on the plan for this:

 - We're making the changes so the worker will observe the `AZURE_FUNCTIONS_` environment variables. This will maintain the behavior we previously had and ensure that the `Debug` environment is automatically set when running under the debugger
 - For the default .NET experience, we'll be updating the default templates to use `CreateDefaultBuilder()` by default (instead of _newing_ up a builder). This will, of course, only impact apps created with the template updates.

For now, the immediate recommendation would be to replace ` new HostBuilder()` with `Host.CreateDefaultBuilder()` and set the environment values you'd typically use in .NET. Once the worker package is updated, you'd get the same behavior for the Azure Functions environment variables.
