### ISSUE TITLE
The repo needs CHANGELOG.md

### ISSUE THREAD

**Issue by Mithras** [Azure/azure-functions-dotnet-worker#428]
Please add CHANGELOG.md.

**Comment by devlead** [comment]
A note on this 1.2.0 seems to be on NuGet since 10 days ago.
https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/1.2.0

but there's no corresponding release/tag here on GitHub
https://github.com/Azure/azure-functions-dotnet-worker/releases

Maybe look at something like GitReleaseManager so releases/notes could be automated as part of CI
https://github.com/GitTools/GitReleaseManager

**Comment by fabiocav** [comment]
The goal would be to track this in the releases.

About @devlead's point, yes, there is a missing release due to an issue with the current pipeline. We'll backfill that. 

Is the release process sufficient for your needs, @Mithras?

**Comment by Mithras** [comment]
@fabiocav yes, as long as I can find what changed between version X and Y, it's sufficient. Thank you!

**Comment by fabiocav** [comment]
Sounds good. Our plan is to continue to leverage GitHub releases for that. Closing this as resolved. Thank you!
