### ISSUE TITLE
maxAutoRenewDuration or maxAutoLockRenewalDuration and relationship to RetryPolicy

### ISSUE THREAD

**Issue by redtaped** [Azure/azure-functions-dotnet-worker#437]
Should we be using maxAutoRenewDuration or the newer maxAutoLockRenewalDuration for changing the lock renewal?

Also, how is this related to retry? If the lock duration of a message is 5 minutes, and we retry 3 times, with a 4:59 minute delay, would the function automatically renew the lock on retry? Would the max auto renew duration setting reset for each retry attempt, or does this value have to be larger than the entire estimated runtime, including retries and delays between retries?

**Comment by SeanFeldman** [comment]
I _think_ because the actual trigger is still using ASB SDK track 1 (`Microsoft.Azure.ServiceBus`) it would be [`MaxAutoRenewDuration`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.messagehandleroptions.maxautorenewduration?view=azure-dotnet). When the underlying implementation moves over to ASB SDK track 2 (`Azure.Messaging.ServiceBus`), [`MaxAutoLockRenewalDuration`](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusprocessor.maxautolockrenewalduration?view=azure-dotnet) will be the value. I think 🙂

**Comment by redtaped** [comment]
Can you help me understand how this value is affected during retries? Would the max auto renew duration setting reset for each retry attempt, or does this value have to be larger than the entire estimated runtime, including retries and delays between retries?

If the lock duration of a message is 5 minutes, and we retry 3 times, with a 4:59 minute delay, would the function automatically renew the lock on retry?

**Comment by fabiocav** [comment]
@redtaped for any of the bindings/extensions with built in support for retries, the guidance is to use that support instead of the retry policy. 

Retry policy is also in preview/beta, and we'll be publishing some guidance around that as it gets to completion.

**Comment by fabiocav** [comment]
@SeanFeldman's comment is also correct. The extensions targeting the track 2 SDK will be available soon, but currently, the documentation [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp) is what applies
