### ISSUE TITLE
Error handling and retries based on policy?

### ISSUE THREAD

**Issue by devlead** [Azure/azure-functions-dotnet-worker#456]
With functions version >= 3.0.23 it's possible to add policies for how errors and retries are handled i.e.
```csharp
[FunctionName("MyFunction")]
[FixedDelayRetry(5, "00:00:10")]
public static async Task Run(
```
or
```csharp
[FunctionName("MyFunction")]
[ExponentialBackoffRetry(5, "00:00:04", "00:15:00")]
public static async Task Run(
```
docs for this at: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#retry-policies-preview

What's the recommended way to achieve the same thing with .NET isolated process functions? Is there something similar or does one have to roll own here?

**Comment by khebul** [comment]
I would also like to know that. I am currently in the process of migrating our current solution to dotnet-isolated worker, and ability to configure retry behaviour is quite important.

**Comment by fabiocav** [comment]
This is planned and in progress. Part of the work has been done [here](https://github.com/Azure/azure-functions-dotnet-worker/pull/357), but the PR was blocked due to a host issue that has been addressed in the release that just went out. We should be able to move that forward now and will have updates to the PR as well as a sample.

Closing this, but will continue to update the issue associated with the PR.
