### ISSUE TITLE
How to configure ServiceBus trigger using Azure.Core (TokenCredential)

### ISSUE THREAD

**Issue by Matthewsre** [Azure/azure-functions-dotnet-worker#468]
Now that we have full access to the HostBuilder, we should be able to configure service bus using TokenCredential provided by Azure.Core. 

I don't see any documentation for how to configure this so that I no longer need to have a connection string with a secret in the Azure Function configuration settings. Is there any guidance for how we could do this while configuring the host?

I have a ChainedTokenCredential I use in my services that preferences using MSI.

For clarity, I would expect to be able to use the following on the HostBuilder:

```
var host = new HostBuilder()
     .ConfigureFunctionsWorkerDefaults((builderContext, applicationBuilder) => 
     {
           // TODO: Configure service bus with TokenCredentials

          applicationBuilder.AddServiceBusClient(builderContext.Configuration.GetSection("ServiceBus")).WithCredential(new Azure.Identity.DefaultAzureCredential());
     })
```

**Comment by fabiocav** [comment]
The worker doesn't control that, so that option is not available there and is still driven by the extension being used.

The track 2 extensions are currently in beta and we'll be creating the bindings for them here as well, once that is in place, you'll be able to use the features listed here: https://devblogs.microsoft.com/azure-sdk/introducing-the-new-azure-function-extension-libraries-beta/
