### ISSUE TITLE
How do you migrate from functions that are netcoreapp3.1 to dotnet 5?

### ISSUE THREAD

**Issue by irwinwilliams** [Azure/azure-functions-dotnet-worker#475]
I started this project in netcoreapp3.1 but would like to flip it to dotnet 5. 
I see this information about [necessary packages](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#package-references) but what else should I do to make it work?

**Comment by trailmax** [comment]
We've run into the same issue - lack of documentation is killing this .Net 5 effort.

**Comment by twentytwokhz** [comment]
@trailmax I totally feel the pain

**Comment by brettsam** [comment]
I don't know that we've got an official migration guide with examples. There's [this](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#differences-with-net-class-library-functions), but that doesn't really take you step-by-step.

Let me see if I can start a wiki page here to quickly start collecting concrete examples. We can use that as a basis for an official doc page.

In the meantime, there are several samples in the repo [here](https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples) that may help. One of the projects includes a sample for every supported extension, for example.

If you've bumped into a migration step that you're stuck at, could you give a concrete example here? That'd help us prioritize.

/cc @ggailey777 as FYI.

**Comment by trailmax** [comment]
@brettsam I've gone through that document and it is fine if you are starting from scratch. I've seen all the samples. But if you are migrating already established project, it is a total pain of trail and error. I've followed this [guide](https://codetraveler.io/2021/05/28/creating-azure-functions-using-net-5/), this guide got me there like 90%. Some bits I had to figure out for myself:
* I've been cought with `[FunctionName("MyFunc")]` vs `[Function("MyFunc")]`. Only `[Function]` works in .Net 5, but both compile for some reason. Wasted days on this, as the function runtime just can't find the function bindings, but no other error messages.
* Value for `FUNCTIONS_WORKER_RUNTIME` in `settings.json` had to be updated from `dotnet` to `dotnet-isolated` locally and in Azure Portal (and in all the slots if they were used).

**Comment by brettsam** [comment]
These are great, thank you @trailmax!

Re: `[FunctionName]` -- Two of the steps in the migration guide should probably be:
1. Remove references to all nuget packages that contain `WebJobs` in the name. You shouldn't see the `WebJobs` namespace in any packages or `using` statements.
2. Remove package reference to `Microsoft.NET.Sdk.Functions`.

**Comment by trailmax** [comment]
@brettsam yeah, removing these packages from dependency chain (eventually) fixed it. I had WebJob packages in sub-sub dependency of Az Func project, hence it was available. After all the functions projects in the solution were converted and WebJob nugets were removed from everywhere, that stopped compiling.

**Comment by RichMercer** [comment]
> These are great, thank you @trailmax!
> 
> Re: `[FunctionName]` -- Two of the steps in the migration guide should probably be:
> 
> 1. Remove references to all nuget packages that contain `WebJobs` in the name. You shouldn't see the `WebJobs` namespace in any packages or `using` statements.
> 2. Remove package reference to `Microsoft.NET.Sdk.Functions`.
> 
> Edit: We also should be able to add support in our Analyzer to catch refs to WebJobs -- filed #479

In my Function project I also did a find and replace to swap out the `ILogger log` parameter passed in to the functions Run method with `FunctionContext context`. A lot of these updates can be done quickly with Find/Replace (e.g. replacing FunctionName with Function). For me there was minimal refactoring other than having to deal with the missing methods in the Cosmos binding. My code was leaning heavily on `doc.GetPropertyValue<string>("value");` so I had to handle that differently.

**Comment by ak37165** [comment]
There are other changes needed as well as we are discovering during migration.

1. You could extract the client IP using request.HttpContext.Connection.RemoteIpAddress in .netcoreapp3.1 but the isolated process does not have access to the HttpRequest. So you need a different method to extract it from HttpRequestData. No documentation, but from experimentation it seems you can look for headers X-Forwarded-For AND x-forwarded-for. The first IP in the list of IP addresses in the value for that header seems to be the relevant client IP. There is a header "client-ip" as well but that does not have the correct value. Some documentation on this would be much appreciated.
2. If the request body is not JSON but Form-encoded, then HttpRequest used to have request.Form. There does not seem to be any equivalent for HttpRequestData.
3. If you encode and decode the JSON strings in your code using Newtonsoft.Json, then camelCase vs PascalCase is automatically handled. With System.Text.Json, you need extra code to handle that. With .Net5.0, the Program.cs has a call to ConfigureFunctionsWorkerDefaults and this seems to add support for camelCase by default (that is good). However, it may not affect the behavior for your own use of the System.text.Json serializer. You need to be careful about that.
4. Running on local host with HTTPS: this requires you to run from command line and not from Visual Studio. So each time you have to debug, you need to attach the debugger. Good thing is this is documented.
5. The HttpTrigger signature has changed. If your project has hundreds of APIs, this can be quite a bit of work to add "logger = functionContext.GetLogger...", change the return types in the functions and related methods, change the way you generate the response etc. This is documented.

We were forced to migrate from 3.1 to 5.0 because we use Azure.Security.KeyVault.Keys which works fine locally but when you deploy to Azure functions, it hits a missing method exception - likely because the System.text.Json version in functions host is pinned to an older version than what Azure.Security.Keyvalut.Keys expects. Using .Net5.0 allows us to avoid such issues.

**Comment by HMoen** [comment]
@ak37165, thanks for your insight. Linking #366 for points 2 and 6 above.

**Comment by harveytriana** [comment]
The signalR topic with Azure functions has deep differences. I have published an article on this. I compare the two scenarios, isolated and traditional: https://www.blazorspread.net/blogview/blazor-y-faas-(parte-2)

**Comment by dolphinspired** [comment]
I've recently been stumbling through the 3.1 -> 5.0 upgrade process for a few Functions. I'd like to add this important note about ApplicationInsights. For the old in-process Functions, [this document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#logging-services) states the following:

> Don't add AddApplicationInsightsTelemetry() to the services collection, which registers services that conflict with services provided by the environment.

This is no longer true for isolated Functions - you _do_ need to register ApplicationInsights during your Program startup. If you don't add it, you'll end up with a dependency injection error like this:

> Exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.ApplicationInsights.TelemetryClient'

To resolve this, you'll specifically need to add a PackageReference for [Microsoft.ApplicationInsights.WorkerService](https://www.nuget.org/packages/Microsoft.ApplicationInsights.WorkerService/), and reference it on startup like this:
```csharp
public static void Main(string[] args)
{
    var host = new HostBuilder()
        .ConfigureServices(services =>
        {
            services.AddApplicationInsightsTelemetryWorkerService();
        })
        .ConfigureFunctionsWorkerDefaults()
        .Build();

        host.Run();
    }
}
```
