### ISSUE TITLE
Create Track 2 (5.x) Microsoft.Azure.WebJobs.Extensions.Storage extension

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-dotnet-worker#498]
Create extension tracking/mapping to latest versions.

**Comment by iscottb122** [comment]
Is this the best issue to track integration of the lovely `Azure.Identity` (`DefaultAzureCredential`) secretless configuration into the `Microsoft.Azure.Functions.Worker.Extensions.Storage` package? Your comments on [this blog post](https://devblogs.microsoft.com/azure-sdk/introducing-the-new-azure-function-extension-libraries-beta/) suggest that it is the correct issue for the Worker (dotnet-isolated) model, but this issue name appears to refer to the `WebJobs` package rather than the `Functions.Worker` package.

Either way, big +1 for this feature for the Worker model. Would be fantastic to move away from connection strings with secrets in the config. We also tried and failed to get a KeyVault layer of indirection working, but won't need to worry about that with this magic.
