### ISSUE TITLE
ILogger missing LogMetric extension method

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-dotnet-worker#543]
In Functions v2 (in proc) we had [an extension method defined in `Microsoft.Azure.Webjobs.Host` that allowed logging of AppInsights `metric` types](https://github.com/Azure/azure-webjobs-sdk/blob/206e194e03d82a101a6b5dffb7b4c3904730801d/src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/LoggerExtensions.cs) but this doesn't exist in the new `Worker.*` namespaces. We should bring it forward.

**Comment by fabiocav** [comment]
Thanks for the PR here @brandonh-msft 

Assigning to @brettsam for initial feedback.

**Comment by tomkerkhove** [comment]
This is maybe the good time to ask the question, but have you considered embracing something like Serilog?

We have standardized on that so that you can write telemetry how you want to, and then it's optimized for multiple sinks. See https://www.codit.eu/blog/announcing-arcus-observability/ or https://github.com/arcus-azure/arcus.observability

**Comment by fabiocav** [comment]
The host changes have now been merged. We'll keep this open to track the worker changes, which will come after a host release.

**Comment by fabiocav** [comment]
Still pending a host release. Flagging as blocked and adding to project for review.
