### ISSUE TITLE
Multiple Azure SignalR Service Instances Support

### ISSUE THREAD

**Issue by jairzjunior** [Azure/azure-functions-dotnet-worker#566]
I would like to use multiples **AzureSignalRConnectionString** to connect with Azure SignalR Service. But I can't do it on Azure Function with **.NET 5**.
I was trying to follow this documentation [Multiple Azure SignalR Service Instances Support in Azure Functions](https://github.com/Azure/azure-functions-signalrservice-extension/blob/dev/docs/sharding.md), but it looks like that works only in a **.NET Core App 3.1** version that uses **Microsoft.Azure.WebJobs.Extensions.SignalRService** package.

**Comment by anthonychu** [comment]
@JialinXin Are you able to help with this?

**Comment by Y-Sindo** [comment]
According to [this line](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.SignalRService/Properties/AssemblyInfo.cs#L6), seems `Microsoft.Azure.Functions.Worker.Extensions.SignalRService` 1.2.2 is a wrapper around `Microsoft.Azure.WebJobs.Extensions.SignalRService` 1.2.2. The extension for .NET Core App 3.1 supports multiple connection strings since 1.3.0, and now the latest version is 1.5.0. Can the extension for .NET 5 upgrade to 1.5.0 to support multiple connection strings? @anthonychu

**Comment by anthonychu** [comment]
Thanks @Y-Sindo. Can you submit a PR to update that metadata?

**Comment by Y-Sindo** [comment]
@anthonychu As SignalR extension has added two input bindings for the multiple endpoints feature, I tried to update the sample and the [sample project reference](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/samples/Extensions/Extensions.csproj#L25), but the build failed because didn't found the Microsoft.Azure.Functions.Worker.Extensions.SignalRService 1.5.0 . Should the sample project reference the local extension projects so that we can update the extension projects and the sample project in the same commit?

**Comment by Y-Sindo** [comment]
@anthonychu I created a PR.

**Comment by jairzjunior** [comment]
Hi guys, any updates about that?

**Comment by Y-Sindo** [comment]
@jairzjunior The 1.7.0 version is released with multiple instances support. Please have a try.
