### ISSUE TITLE
Azure function 5 and EF Core 5 Could not load file or assembly > Microsoft.Extensions.DependencyInjection.Abstractions

### ISSUE THREAD

**Issue by rlamba89** [Azure/azure-functions-dotnet-worker#567]
> System.IO.FileNotFoundException : Could not load file or assembly
> 'Microsoft.Extensions.DependencyInjection.Abstractions,
> Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
> The system cannot find the file specified.

I am getting above error when running the tests in azure devops pipeline but not when running it local. Everything works locally fine.

I believe the error happens when the base class try to initialize DB Context using EF Core 5 at line 15. 

[![enter image description here][1]][1]

Code stack:

**Azure function isolated enabled .Net 5**

**EF Core 5**

Can someone please help me understand why this is happening? Below is the screenshot of the packages referenced in the test project.

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/8CE4n.png
  [2]: https://i.stack.imgur.com/tBil6.png

**Comment by BrandonSchreck** [comment]
I'm having a similar issue when deployed in Azure. Locally I can run my application without any issues, but when deployed I'm getting the same error: 

`System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`

It looks like it is throwing an exception when I'm attempting to setup dependency injection in Program.cs.

```
.ConfigureServices((builderContext, serviceCollection) => {
    var someBaseUrl = builderContext.Configuration.GetValue<string>("SOME_BASE_URL");
    serviceCollection.AddHttpClient("ApiClient", client => client.BaseAddress = new Uri(someBaseUrl));
    serviceCollection.AddSingleton<ISomeService, SomeService>();
})
```

When I open up the NuGet Packages, I have Microsoft.Azure.Functions.Worker (v1.4.0) installed which contains a dependency on Microsoft.Extensions.Hosting.Abstractions (v5.0.0) which contains the Microsoft.Extensions.DependencyInjection.Abstractions (v5.0.0) dependency.

I've tried explicitly installing Microsoft.Extensions.DependencyInjection (v5.0.2) and Microsoft.Extensions.DependencyInjection.Abstractions (v5.0.0), but once deployed I get the same exception when calling a simple Healthcheck (returns 200 Ok status and message) azure function.

My .csproj is as follows:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <UserSecretsId>00000000-0000-0000-0000-000000000000</UserSecretsId>
    <ProjectGuid>FC5C1F84-F335-4D92-8753-A36C63CBAA10</ProjectGuid>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.4.1" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.4" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.4.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.12.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

I'm going to play around with this some more and see if I can identify the root cause, which I think is either AddHttpClient or AddSingleton. Maybe downgrading to Microsoft.Azure.Functions.Worker v1.3 might be helpful too.

**Comment by brettsam** [comment]
Can either of you confirm that .NET 5.0 is installed on the machines that you're running on? This seems like the framework may be missing...

**Comment by BrandonSchreck** [comment]
> Can either of you confirm that .NET 5.0 is installed on the machines that you're running on? This seems like the framework may be missing...

Locally, yes I have .NET 5 (5.0.401) installed.

If I publish the Azure Function directly from Visual Studio to Azure (Build -> Publish AzureFunction) the functions works correctly. However, if we build through Azure DevOps CI/CD pipeline, it doesn't work. While the deploy/publish is successful it throws an exception when trying to call the Azure Function (System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60')
