### ISSUE TITLE
Net SDK (in-proc) and worker SDK (isolated) should throw an error when installed on the same csproj

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-dotnet-worker#618]
If the user installs https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/ and https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/ on the came csproj file the build process should throw a compile error

**Comment by MironAtHome** [comment]
What a dumb ass request.
They should be able to work on the same function app, coexisting.
One, working in - process, the other onoe using new isolated runtime.
Else, it would mean that entire industry has to redevelop a new set of Azure Function solutions, in order to move forward. That would be a precipice to forcing Azure cloud customers to competitors, who aren't as hostile to their customer base.

**Comment by SeanFeldman** [comment]
Wherever you think it's the wrong request or not, articulate your thoughts w/o offending people. Be better than that.

**Comment by jeffhollan** [comment]
< Removing some comments that violate our open source code of conduct > https://opensource.microsoft.com/codeofconduct/

**Comment by fabiocav** [comment]
Flagging for triage/review

@stefanushinardi FYI

**Comment by kshyju** [comment]
Fixed by #841

We currently produce a build error when an isolated function app has a reference to `Microsoft.NET.Sdk.Functions` package.

![image](https://user-images.githubusercontent.com/144469/196556274-1db57050-f5d0-4e52-a711-4c5052daddb6.png)
