### ISSUE TITLE
Out Of Memory

### ISSUE THREAD

**Issue by jerry2007** [Azure/azure-functions-dotnet-worker#761]
I have azure function which returning data from Cosmos Db.
When the data is larger than 5MB, azure function call crashed on OutOfMemory Exception.

This happening just in Azure. On localhost it works ok.

I tried streamimg of response, but it is not supported.
```
public IAsyncEnumerable<Requirement> GetRequirements([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)] HttpRequestData request, FunctionContext functionContext)
        {
            var username = functionContext.GetUsername();
            return _inboxDbContext.Set<Requirement>().Where(p => p.Username == username && !p.Downloaded).AsAsyncEnumerable();
        }
```
Can you help me?

**Comment by vvopenka** [comment]
Here is a code which fails locally as well, writing directly to Body of a response.

Here is a code which fails locally as well:
```
public class ComplexObject
{
    public string Data { get; set; }
    public ICollection<ComplexObject> ComplexObjects { get; set; }
}

public class Function
{
    [Function("Test")]
    public async Task<HttpResponseData> GetRequirements([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)] HttpRequestData req, FunctionContext functionContext)
    {
        HttpResponseData response = req.CreateResponse();
        response.StatusCode = HttpStatusCode.OK;
        response.Headers.Add("Content-Type", "application/json");
        IAsyncEnumerable<ComplexObject> data = GetData();
        await JsonSerializer.SerializeAsync(response.Body, data, options: new JsonSerializerOptions
        {
            Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
        });
        return response;
    }

    private async IAsyncEnumerable<ComplexObject> GetData()
    {
        await Task.CompletedTask;
        for (int i = 0; i < 100; i++)
        {
            yield return GetObject(0);
        }
    }

    private ComplexObject GetObject(int depth = 0)
    {
        ComplexObject complexObject = new ComplexObject();
        complexObject.Data = BigData;
        complexObject.ComplexObjects = new List<ComplexObject>();
        if (depth < 5)
        {
            for (int i = 0; i < 10; i++)
            {
                complexObject.ComplexObjects.Add(GetObject(depth + 1));
            }
        }
        return complexObject;
    }

    private const string BigData = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Integer imperdiet lectus quis justo. Maecenas libero. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Aliquam in lorem sit amet leo accumsan lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nunc dapibus tortor vel mi dapibus sollicitudin. Suspendisse nisl. Maecenas lorem. Morbi scelerisque luctus velit. Aliquam ante. Aliquam erat volutpat. Integer malesuada. In rutrum. Aenean id metus id velit ullamcorper pulvinar.";
}
```

**Comment by kshyju** [comment]
@jerry2007 Just to confirm, are you sure that it works when the data size is smaller, and you use `IAsyncEnumerable<T>` as the return type? Are you getting a collection of `Requirement`s when executing this function?

**Comment by jerry2007** [comment]
@kshyju nope...
`IAsyncEnumerable<T>` is not supported completly

But when the data is bigger then 5MB, deployed in Azure and return type is `IEnumerable<T>`, it crash on Out Of Memory Exception.

**Comment by kshyju** [comment]
@jerry2007 Thank for confirming. Yes. Async stream support is not available today. [This issue](https://github.com/Azure/azure-functions-dotnet-worker/issues/773) will be tracking the progress of that work. We will track the OOM issue here with `IEnumerable<T>` type. May I ask you to update the original code snippet to use `IEnumerable<T>` to keep the context of this issue clean?

**Comment by kshyju** [comment]
@vvopenka Thanks! I tried your repro code. I am not getting any `OutOfMemoryException`. I get the "**_System.IO.IOException: Stream was too long_**" on the `await JsonSerializer.SerializeAsync` line which is inside your function. Here is the top portion of the stack trace I am seeing. Were you getting the same exception or something different?

>  System.IO.IOException: Stream was too long.
[2022-01-10T22:25:41.145Z]    at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
[2022-01-10T22:25:41.149Z]    at System.IO.MemoryStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
[2022-01-10T22:25:41.152Z] --- End of stack trace from previous location ---
[2022-01-10T22:25:41.153Z]    at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
[2022-01-10T22:25:41.154Z]    at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
[2022-01-10T22:25:41.156Z]    at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
[2022-01-10T22:25:41.157Z]    at _761_OutOfMemory.Function.GetRequirements(HttpRequestData req, FunctionContext functionContext) in C:\Dev\Temp\GHIssues\761-OutOfMemory\Function.cs:line 26

The stack trace suggests the exception is being thrown from the serializer, not from the functions infrastructure/runtime code.

Another thing I noticed while executing your code is the spike in memory usage (just a single execution). It went from under 30 MB to 4 GB. 
![image](https://user-images.githubusercontent.com/144469/148857648-e6978699-123e-447d-aff6-a9b58a7c0ea2.png). 

OOM exceptions are usually caused by a large object graph/large allocations than what the runtime can handle. Could you take a look at [this recommendations](https://docs.microsoft.com/en-us/dotnet/api/system.outofmemoryexception?view=net-6.0#remarks) to prevent OOM and see any of this makes sense/can be adopted in your case?

**Comment by vvopenka** [comment]
@kshyju Sorry, OutOfMemory exception is thrown when you deploy the function to Azure Function. The stack trace there looks like this:

> Exception: System.AggregateException: One or more errors occurred. (Exception of type 'System.OutOfMemoryException' was thrown.)
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)

Locally it does indeed IOException. I think it's connected to the memory limit of the environment it runs on.

Just to be clear, we do not insist on returning IAsyncEnumerable. We just need to stream a big amount of data out of our Function which currently fails due to the output stream being a MemoryStream and so we are hitting the memory limits.

**Comment by jerry2007** [comment]
> @jerry2007 Thank for confirming. Yes. Async stream support is not available today. [This issue](https://github.com/Azure/azure-functions-dotnet-worker/issues/773) will be tracking the progress of that work. We will track the OOM issue here with `IEnumerable<T>` type.
> 
> I tried to repro this issue by returning a 10 MB string and I do not see any issues. Could you please share a minimal repro of OOM issue using `IEnumerable<T>` and the stack trace of the exception?

Here is Minimal project...
[InboxMin.zip](https://github.com/Azure/azure-functions-dotnet-worker/files/7854809/InboxMin.zip)

When this project is deployed to azure (consuption mode) you can try these requests:

https://solitea-inbox-staging.azurewebsites.net/api/Sample1?maxlevel=5&itemscount=4 - OK
https://solitea-inbox-staging.azurewebsites.net/api/Sample1?maxlevel=5&itemscount=5 - Out Of Memory
https://solitea-inbox-staging.azurewebsites.net/api/Sample1?maxlevel=10&itemscount=10 - Out Of Memory

**Comment by kshyju** [comment]
@jerry2007 Thanks for sharing the repro. When you use `?maxlevel=10&itemscount=10` for the request, you are building a very huge object graph with your code. You will be able to observe this in the diagnostics tools window in VS when you locally debug this code.

![image](https://user-images.githubusercontent.com/144469/149192006-4afd20ee-dd5b-457c-ac9b-62a0755a3405.png)

The consumption hosting plan has a [max memory threshold](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits) of 1.5 GB. Your code is building a large object which goes beyond this threshold, causing the OOM exception.

You could consider changing to a different hosting plan or revisit your implementation to produce less data in memory. 

https://docs.microsoft.com/en-us/dotnet/api/system.outofmemoryexception?view=net-6.0#remarks

Hope this helps.

**Comment by jerry2007** [comment]
Ok, I realized that my repro is not the best for my situation.
But it is complicated to create repro with my use case...

The usecase is that I have Azure function, which getting data from cosmosDb.
When I run it locally it is ok, return 200 and data. memory consuption in diagnotic tools window is on 668MB.
When I deploy this code to azure and try same request it crash on Out Of Memory Exception:

![image](https://user-images.githubusercontent.com/6752910/149367329-463d2281-498f-49c0-8963-eb70845ed3b3.png)

`HTTP/1.1 500 Internal Server Error
Request-Context: appId=cid-v1:87983616-9030-46bd-8e4f-8ecfcecd5850
Date: Thu, 13 Jan 2022 16:12:00 GMT
Content-Length: 85

AggregateException

Exception of type 'System.OutOfMemoryException' was thrown.

`

![image](https://user-images.githubusercontent.com/6752910/149367402-e75954f0-0321-4f0d-bfe1-120fca9ed8cb.png)

The function code:

`public async Task<IEnumerable<Requirement>> GetRequirements([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)] HttpRequestData req, FunctionContext functionContext)
        {
            var username = functionContext.GetUsername();
            _logger.LogTrace("Getting requirements for username = {UserName}", username);
            var data = await _inboxDbContext.Set<Requirement>().Where(p => p.Username == username && !p.Downloaded).ToListAsync();
            return data;
        }`

Where _inboxDbContext is DbContext of Entity Framework core 6.0.1

**Comment by kshyju** [comment]
Is your production data different (larger object graph) than the one you are using for local development? What is the memory usage you are observing on production where you are getting this OOM exception? Can you try deploying a different hosting plan and see that help with the consumption plan limits? 

Without a local repro, it is hard to point out what is causing it. But in general, OOM exception is thrown when you try to deal with huge amount of data (_Most of the time, the environment limits are main causes than the infra code_). I recommend reviewing the document linked in the previous comment and see what can be done in your app logic to reduce the data size you are handling.

**Comment by jerry2007** [comment]
Production data is same, in fact, i am trying to get only production data in same CosmosDb
But when I trying your advices I founded out, that new Azure function service works but my old one not...

When I create new Azure Function Service in Consuption mode in Azure and deploy same code it works.
But on Azure function Service, which was crated 1 year ago, same code not work and raising Out Of Memory Exception...

Is this ok? Should I just recrete Azure functions Service in Azure?

**Comment by kshyju** [comment]
@jerry2007 Can you double check your old function app uses same settings (isolated version, function runtime version, hosting type etc.) as the new one?

**Comment by jerry2007** [comment]
I did that check and I maybe found that problem...
It looks like 64/32bit problem...
On old one service I had 64bit version on the new one 32bit. After set old one to 64bit it started work.
And one more problem was deployed as Self-Contained. When I deployd app as Self-Contained even on 32bit version it crashed also on OOM. After deploying as Framewokr-dependent it works.

So thank you for help and I will look forward for IAsyncEnumerable support :-)
