### ISSUE TITLE
Durable Functions support in .NET Isolated worker

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-dotnet-worker#767]
This issue tracks adding an extension to support Durable Function triggers.

Related: https://github.com/Azure/azure-functions-dotnet-worker/issues/739

EDIT: Instructions for getting started with the public preview can be found here: https://github.com/microsoft/durabletask-dotnet#usage-with-azure-functions

**Comment by AlexEngblom** [comment]
Where is this going at, any news on possible GA date?

**Comment by cgillum** [comment]
Adding @jviau and @lilyjma.

The current plan is to release another preview before the end of the year, followed by GA early next year. It's taking a bit longer than originally planned because we decided to do some significant refactoring to align this SDK with the patterns used in the broader .NET ecosystem.

**Comment by inmindtechnologies** [comment]
We were expecting this to be ready before the December 3 deadline. It means our Azure Functions (currently on .NET Core 3.1) won't have any security patches after that date. The only option we have would be to first migrate them on Azure Functions 4 using .NET 6 and the in-Process model, but it means that should plan a second migration when .NET 7 isolated is released.

We don't mind waiting until next year, but Microsoft should post pone the deadline so that we can avoid two migrations.

**Comment by AlexEngblom** [comment]
It looks like we won't have durable entity support in the first release. This is a real shame, because for us it means we cannot move forward yet.

**Comment by to-fi** [comment]
any news on that ? we're also blocked to migrate to .NET 7. any timeline would be good !!! currently there is an RC but with a note note to use in production...

**Comment by AlexEngblom** [comment]
So for time being there ain't gonna be rush for NET support except for LTS versions: https://techcommunity.microsoft.com/t5/apps-on-azure-blog/net-on-azure-functions-roadmap-update/ba-p/3619066

**Comment by fabiocav** [comment]
This is now GA: https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-isolated-overview

Closing this as completed, but if you have any problems, questions or feedback, please open issues [here](https://github.com/microsoft/durabletask-dotnet/issues)

Thanks!
