### ISSUE TITLE
Validate function name

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-dotnet-worker#788]
Currently any string value can be used as the function with the `Function` attribute. 
````
[Function("GET /api/modules/")]
````

We have customers who have used special characters like `/` in function names [which caused issues in other areas](https://github.com/Azure/azure-functions-dotnet-worker/issues/777) like getting function keys. The [HostFunctionMetadataProvider has some code path which validates](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Host/HostFunctionMetadataProvider.cs#L99) against the [defined regex expression](https://github.com/Azure/azure-functions-host/blob/dcfd7fc1458da020de2c3f49b1d9672b1e1bc229/src/WebJobs.Script/Utility.cs#L46). But that does not seems to be applicable for the isolated worker case.

Need to be fixed in a non-breaking way (to existing customers).

**Comment by jwyza-pi** [comment]
It appears that version 1.16+ of Microsoft.Azure.Functions.Worker.Sdk "fixed" this in a breaking way.  We have been using `[Function("health/statusz")]` for well over a year on dozens of functions and as soon as we upgrade from 1.15.X to 1.16, that particular function now fails with this error: `The 'health/statusz' function is in error: 'health/statusz' is not a valid function name.`

I'm guessing this is a side effect of the new source generation for the function executors?

**Comment by liliankasem** [comment]
Apologies that we missed this breaking in v1.16 :(

The function name validation started to work as expected when we switched over to using worker indexing (and the new source generator) in the dotnet-worker instead of the 'FunctionMetadataLoaderExtension'. When we were using `FunctionMetadataLoaderExtension`, in the host we followed the [CustomProvider](https://github.com/Azure/azure-functions-host/blob/91e0bf7eca21fb9bb380450cf9d148745b0f4870/src/WebJobs.Script/Host/FunctionMetadataManager.cs#L219) code path. This code path has a bug as it never validates the metadata. When we switched to worker indexing, we end up going down a different path in the host (using the [worker metadata provider](https://github.com/Azure/azure-functions-host/blob/91e0bf7eca21fb9bb380450cf9d148745b0f4870/src/WebJobs.Script/Host/WorkerFunctionMetadataProvider.cs#L126)) that properly validates the function name

The reason this breaking change accidentally happened in v1.16 of the worker SDK is because that is the release where we made `FunctionsEnableWorkerIndexing` true by default. Unfortunately, we cannot revert this breaking change and so the fix will remain in v1.
 
Resolving issue as this change has already been made and validated.
