### ISSUE TITLE
Log user exceptions to application insights directly

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-dotnet-worker#846]
Related to https://github.com/Azure/azure-functions-host/issues/4296

As part of the work going into the above issue to throw a new type of exception for invocation failures, we want to make changes on the worker side to log unhandled user exceptions rather than letting them bubble up to the host - this will give users full exception details, instead of having them all wrapped with RpcException or InvocationException.

The host will still need information on failing invocations and this will be a breaking change, therefore this change should be placed behind a feature flag to avoid duplicate logs.

- [x] Update the RPCException refactor design document with the design and implementation details, including changes to the profobuf (https://github.com/Azure/azure-functions-host/issues/4296)
- [x] Implement worker side exception logging
- [x] Make any corresponding changes in the host

**Comment by JustinGrote** [comment]
I would clarify this that the worker side can *handle* user exceptions rather than *log*, log gave the impression to me that it would just put in an info log, rather than allow the worker to do things like present its own language version of the exception to Application Insights, but still be able to report to the host that the function failed and avoid a duplicate exception (which is what is happening now when I log to insights within my code the exception before letting it continue)

Thanks!

**Comment by kaibocai** [comment]
Hi @liliankasem , for other language worker seems there is no way to directly log to app insight sdk.

**Comment by JustinGrote** [comment]
@liliankasem is this supposedly resolved by #8314?
