### ISSUE TITLE
Conditional middleware

### ISSUE THREAD

**Issue by andersson09** [Azure/azure-functions-dotnet-worker#855]
Can azure functions isolated support conditional middleware?:
.e.g. UseWhen(context =>, appBuilder =>)

I have middleware that I would only like to use with HttpTriggers.

Thanks

**Comment by SeanFeldman** [comment]
Good question. Should be looked at from a broader perspective. What if my middleware is only for Service Bus triggers. Or Blobs.
Theoretically, it's possible by looking at some sort of object in the binding context. This is how I've done in week HTTP triggers out in the middleware. But since there could be any type of trigger, it would require knowing a corresponding type for each trigger to look for.

**Comment by kshyju** [comment]
[Version 1.8.0-preview1](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/) of `Microsoft.Azure.Functions.Worker` package introduces the `UseWhen` extension method which will allow you to register a middleware which gets executed conditionally.

Sample usage.

````
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(workerApplication =>
    {
        workerApplication.UseWhen<StampHttpHeaderMiddleware>((context) =>
        {
            // We want to use this middleware only for http trigger invocations.
            return context.FunctionDefinition.InputBindings.Values
                          .First(a => a.Type.EndsWith("Trigger")).Type == "httpTrigger";
        });
    })
    .Build();
`````

**Comment by andersson09** [comment]
Nice. Thank you.
