### ISSUE TITLE
ServiceBus batch does not work for isolated worker extension.

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-dotnet-worker#906]
An example needed if it's supported.
Based on:
https://github.com/Azure/azure-functions-servicebus-extension/issues/15#issuecomment-1129404763

**Comment by kshyju** [comment]
@alrod @nzthiago 

I investigated this issue on the isolated worker side and found that the language worker is receiving multiple invocation requests from host instead of a single (batched) one. For example, If I send 5 messages to my service bus queue, I get 5 invocation requests (each with unique invocationId value) in the language worker GRPC message receiving layer.

Here is the sample code I used to test.
````
[Function("Function1")]
public void Run([ServiceBusTrigger("myqueue", Connection = "MyServiceBusConnStr")] string[] myQueueItem)
{
    _logger.LogInformation($"Isolated function received {myQueueItem.Length} items");
    foreach (var item in myQueueItem)
    {
        _logger.LogInformation($"C# Isolated processed message: {item}");
    }
}
````
and the host.json used

````
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingExcludedTypes": "Request",
      "samplingSettings": {
        "isEnabled": true
      }
    }
  },
  "ServiceBusOptions": {
    "BatchOptions": {
      "MaxMessageCount": 1000,
      "OperationTimeout": "00:01:00",
      "AutoComplete": "true"
    }
  }
}
````
I tested an in-proc function with same "ServiceBusOptions" section of the host.JSON settings and it worked.

So, it looks like the service bus extension is not sending the correct payload from host to language worker.

**Comment by kshyju** [comment]
_Please ignore my previous reply(deleted now to avoid confusion for future readers)_

I tested this on the isolated worker and found it to be working fine. Here is the function code I used to verify.

````
[Function("Function1")]
public void Run(
            [ServiceBusTrigger("myqueue", Connection = "MyServiceBusConnStr", IsBatched = true)] string[] myQueueItem)
{
    _logger.LogInformation($"Isolated function received {myQueueItem.Length} items");
    foreach (var item in myQueueItem)
    {
        _logger.LogInformation($"C# Isolated processed message: {item}");
    }
}
````
and the host.json

````
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "ServiceBusOptions": {
    "BatchOptions": {
      "MaxMessageCount": 1000,
      "OperationTimeout": "00:01:00",
      "AutoComplete": "true"
    }
  }
}
````



![image](https://user-images.githubusercontent.com/144469/170105600-a15506b5-c5db-48b4-9c3c-4d6e649b2cb0.png)

**Comment by fabiocav** [comment]
@alrod / @nzthiago closing this as this has now been validated and works as expected. Please let us know if you have any additional questions.
