### ISSUE TITLE
The SendGrid return binding does nothing

### ISSUE THREAD

**Issue by sholman** [Azure/azure-functions-dotnet-worker#907]
I have setup a function that uses the return SendGrid Attribute and have added my API key and am returning a SendGridMessage from my function, but no email is ever sent and no error is shown.

Example Function

````
[Function("NewUserNotificationQueue")]
[return: SendGrid(ApiKey = "SendGridAPIKey")]
public static SendGridMessage Run([QueueTrigger("new-user-notification", Connection = "StorageConnectionString")] NewUserNotification newUserNotification,
FunctionContext context)
{
    var logger = context.GetLogger("NewUserNotificationQueue");
    logger.LogInformation($"new-user-notification queue trigger function processed: {newUserNotification}");

    var htmlEmailContent = HtmlEmailHelpers.GenerateNewUserEmail(newUserNotification.PortalUrl, newUserNotification.FirstName);

    if (htmlEmailContent == string.Empty)
    {
        logger.LogError("New user email content is blank!");
        return null;
    }

    var message = new SendGridMessage();

    message.AddTo(newUserNotification.EmailAddress);
    message.SetFrom("myfromaddress@mydomain.com");
    message.AddContent(MimeType.Html, htmlEmailContent);
    message.SetSubject("Welcome to the system");

    return message;
}
````

**Comment by sholman** [comment]
> @sholman Is your QueueTrigger function being executed? Did you verify that by putting a breakpoint in the function code when running locally?

Yes, as per my message above, the code is running and returning a SendGridMessage but nothing is being sent.

**Comment by kshyju** [comment]
What is this `SendGrid` attribute? Where is it coming from? For the isolated model, you should use the [SendGridOutput ](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.SendGrid/src/SendGridAttribute.cs#L12)attribute.

Due to the issue mentioned [here](https://github.com/Azure/azure-functions-dotnet-worker/issues/737), you cannot return an instance of `SendGridMessage` as the return value of the function, instead you should [return the JSON string produced using JSON.NET serializer](https://github.com/Azure/azure-functions-dotnet-worker/issues/737#issuecomment-991403796).

Here is a working example, Here I am using an HttpTrigger, but it should work for any other trigger as well.

````
[Function("Function1")]
[SendGridOutput(ApiKey = "SendGridApiKey")]
public string Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req)
{
    var htmlEmailContent = $"<h2>Hello {DateTime.Now}</h2>";

    var message = new SendGridMessage();
    message.SetFrom(new EmailAddress("foo@bar.com", "Foo"));
    message.SetGlobalSubject($"Hi {DateTime.Now}");
    message.AddTo(new EmailAddress("bar@foo.com", "Bar"));
    message.AddContent(MimeType.Html, htmlEmailContent);

    // Use Newtonsoft JSON serializer to produce JSON string. 
    var messageJson = Newtonsoft.Json.JsonConvert.SerializeObject(message);

    return messageJson;
}
````
Hope this helps. Let us know if you still have questions.

**Comment by sholman** [comment]
Ok, thanks. I couldn't find where the SendGridOutput was referenced from. 

I had Microsoft.Azure.Functions.Worker in my usings but it said it couldn't find that attribute which is what threw me.

I have switched back to the in-proc functions for this now and got it working immediately.

**Comment by kshyju** [comment]
For isolated functions, you need to add a package reference to [Microsoft.Azure.Functions.Worker.Extensions.SendGrid](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.SendGrid/). The `SendGridOutput` attribute is defined in this package.
