### ISSUE TITLE
Activity.Current null in isolated Azure Function v4 in .NET 6

### ISSUE THREAD

**Issue by debasish-das-it** [Azure/azure-functions-dotnet-worker#914]
Activity.Current appears null in isolated Azure Function v4 in .NET 6. can some one help me to fix this issue.

**Following my project .csproj content.**
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>    
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Clients\**" />
    <EmbeddedResource Remove="Clients\**" />
    <None Remove="Clients\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.6.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="1.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
    <None Update="swagger.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>`

**Comment by fabiocav** [comment]
This should be addressed.

Notes for the logic:
- If the trace context passed into the worker is populated with a parent ID, we should reuse that ID for the activity.
- Otherwise; an activity should be created using the invocation ID.

**Comment by debasish-das-it** [comment]
@[fabiocav](https://github.com/fabiocav) Not sure how to achieve that.

**Comment by debasish-das-it** [comment]
Any Update on this?

**Comment by getsetcode** [comment]
We have the same problem here. `CosmosDbTrigger` and trying to write telemetry using `TelemetryClient`. By default any custom events or exceptions we're writing don't have operation context, and we can't add explicitly because in the code `Activity.Current` is null. Currently exploring work-around by wrapping the function code in a `new System.Diagnostics.Activity`, but it'd be good to know the correct approach.

**Comment by RohitRanjanMS** [comment]
@debasish-das-it you can start an activity by using the traceparent form the context. 
 
string traceparent = <get the traceparent from TraceContext.Attributes>
            Activity activity = activitySource.StartActivity("your activity", ActivityKind.Internal, traceparent);

**Comment by debasish-das-it** [comment]
> 

@getsetcode. can you please share the working approach code.

**Comment by sahayaarockiamary** [comment]
@debasish-das-it  I am also facing this issue. Did you find any solution to resolve this?

**Comment by jviau** [comment]
General advice, whether this is a bug or not, always check for `null` on `Activity.Current`. As an optimization, activities are only created if someone is actively listening to them. In the case an activity source has listeners, `Activity.Current` _can be null_.

See [here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/ActivitySource.cs#L169)

**Comment by lufthavn** [comment]
I'm also experiencing this with a ServiceBusTrigger on a brand new .NET isolated v4 function. 

Our basic setup setup is API -> topic -> function #1 -> queue -> function 2. In application insights, I get telemetry up to and including function #1. The subsequent telemetry in the entire operation is not correlated. I tried debugging function #1 and can see that Activity.Current is null, which is a bit confusing since the telemetry from function #1 is correlated. 
But since I can't access the Correlation ID on the current activity in function #1, I can't fetch it to set it on the message that goes to function #2. 

Maybe switching to using an output binding, instead of using the Service Bus SDK will fix this? But it would be nice to be able to access the correlation ID for other purposes.

**Comment by sahayaarockiamary** [comment]
@fabiocav Any update on when the development will be complete and we can refer Activity.Current in Azure Functions?

**Comment by jviau** [comment]
We don't have any update for this at the moment, but we are evaluating the observability experience in Functions and will get back to this soon.

**Comment by Qualizorg** [comment]
Any news?

**Comment by jviau** [comment]
Can you try the latest AppInsights preview package? https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.ApplicationInsights/1.0.0-preview4

**Comment by jviau** [comment]
@Qualizorg - this would be directly related to that: https://github.com/Azure/azure-functions-host/issues/9273

**Comment by jviau** [comment]
Closing this as it is addressed by the preview package.
